"""Add SupportPlan hierarchy and Sabikan responsibility tables

Revision ID: 1752f247da8c
Revises: 4c6d5dcc197e
Create Date: 2025-10-25 15:38:02.524451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1752f247da8c'
down_revision = '4c6d5dcc197e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sabikan_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sabikan_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_plan_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['support_plan_id'], ['support_plans.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitorings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('sabikan_id', sa.Integer(), nullable=False),
    sa.Column('monitoring_date', sa.Date(), nullable=True),
    sa.Column('progress_score', sa.Integer(), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.Column('next_plan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['support_plans.id'], ),
    sa.ForeignKeyConstraint(['sabikan_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_term_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_plan_id', sa.Integer(), nullable=False),
    sa.Column('short_goal', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['support_plan_id'], ['support_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specific_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_term_goal_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('responsible_supporter_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('is_custom_task', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['short_term_goal_id'], ['short_term_goals.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['service_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specific_goal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'specific_goals', ['specific_goal_id'], ['id'])

    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sabikan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('comprehensive_policy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_challenges', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'supporters', ['sabikan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_challenges')
        batch_op.drop_column('user_strengths')
        batch_op.drop_column('comprehensive_policy')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('sabikan_id')

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('specific_goal_id')

    op.drop_table('specific_goals')
    op.drop_table('short_term_goals')
    op.drop_table('monitorings')
    op.drop_table('comments')
    op.drop_table('assessments')
    op.drop_table('service_templates')
    # ### end Alembic commands ###
