"""add_pin_hash_and_contact_to_user

Revision ID: 7517e58e57fc
Revises: 9eb7f5da0b31
Create Date: 2025-10-25 18:11:52.330464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7517e58e57fc'
down_revision = '9eb7f5da0b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_consent_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('user_agreement_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agreement_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('user_consent_date')

    # ### end Alembic commands ###
