"""add_pin_hash_and_contact_to_user

Revision ID: 9eb7f5da0b31
Revises: 1752f247da8c
Create Date: 2025-10-25 17:47:29.947013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb7f5da0b31'
down_revision = '1752f247da8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.drop_column('short_goal')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=128), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('pin_hash')
        batch_op.drop_column('phone')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_goal', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
