"""fix: added missing plan_start_date and plan_end_date to SupportPlan

Revision ID: 01f8d85d4a05
Revises: 58f6f847af97
Create Date: 2025-11-29 11:54:08.676158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f8d85d4a05'
down_revision = '58f6f847af97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('plan_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.drop_column('plan_end_date')
        batch_op.drop_column('plan_start_date')

    # ### end Alembic commands ###
