"""feat: finalized core models for finance, support log, and timecard

Revision ID: 04b649b976fc
Revises: 01f8d85d4a05
Create Date: 2025-11-29 15:12:12.821431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04b649b976fc'
down_revision = '01f8d85d4a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_unit_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=False),
    sa.Column('commit_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_log_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=False),
    sa.Column('support_goal_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('support_start_time', sa.DateTime(), nullable=False),
    sa.Column('support_end_time', sa.DateTime(), nullable=False),
    sa.Column('work_preparation_minutes', sa.Integer(), nullable=True),
    sa.Column('support_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.ForeignKeyConstraint(['support_goal_id'], ['individual_support_goals.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_goal_id'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_supporter_id'))
        batch_op.drop_constraint(batch_op.f('daily_logs_approver_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('daily_logs_supporter_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('daily_logs_goal_id_fkey'), type_='foreignkey')
        batch_op.drop_column('daily_goal_commitment')
        batch_op.drop_column('tardiness_minutes')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('support_method')
        batch_op.drop_column('early_leave_minutes')
        batch_op.drop_column('approver_id')
        batch_op.drop_column('actual_start_time')
        batch_op.drop_column('actual_end_time')
        batch_op.drop_column('goal_id')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('user_lifestyle_notes')
        batch_op.drop_column('supporter_id')
        batch_op.drop_column('work_preparation_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_preparation_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supporter_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_lifestyle_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('actual_end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approver_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('early_leave_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('support_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tardiness_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daily_goal_commitment', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('daily_logs_goal_id_fkey'), 'individual_support_goals', ['goal_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('daily_logs_supporter_id_fkey'), 'supporters', ['supporter_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('daily_logs_approver_id_fkey'), 'supporters', ['approver_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_daily_logs_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_goal_id'), ['goal_id'], unique=False)

    op.drop_table('daily_log_activities')
    op.drop_table('service_unit_master')
    # ### end Alembic commands ###
