"""add void fields to service certificate

Revision ID: 06bfd980e0c2
Revises: 505a317e3f2d
Create Date: 2026-06-13 12:22:05.884942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bfd980e0c2'
down_revision = '505a317e3f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voided_by_supporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('voided_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('void_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'supporters', ['voided_by_supporter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('void_reason')
        batch_op.drop_column('voided_at')
        batch_op.drop_column('voided_by_supporter_id')

    # ### end Alembic commands ###
