"""Added staff_code and absence_plan_link for compliance

Revision ID: 073b79276d87
Revises: 56ae7526946c
Create Date: 2025-11-23 17:13:59.443461

"""
from alembic import op
import sqlalchemy as sa
# PythonのUUIDライブラリをインポートし、一意のコードを生成するために使用します
import uuid 


# revision identifiers, used by Alembic.
revision = '073b79276d87'
down_revision = '56ae7526946c'
branch_labels = None
depends_on = None

def upgrade():
    # ### 1. staff_code を一旦 nullable=True で追加する (NULL値挿入エラー回避) ###
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        # NOTE: unique=True も一旦削除するか、次のステップで追加します。
        #       ここでは NOT NULL 違反回避を優先します。
        batch_op.add_column(sa.Column('staff_code', sa.String(length=20), nullable=True, index=True, unique=True)) 
    
    # ### 2. 既存のレコードに一意のコードを挿入する ###
    # 既存のSupporterテーブルの参照を作成
    supporter_table = sa.Table('supporters', sa.MetaData(), 
                               sa.Column('id', sa.Integer, primary_key=True),
                               sa.Column('staff_code', sa.String(length=20)))
    
    # DBコネクションの取得と全職員のID取得
    connection = op.get_bind()
    results = connection.execute(sa.select(supporter_table.c.id)).fetchall()

    for row in results:
        supporter_id = row[0]
        # 既存職員ごとにランダムな一意のコードを生成（例: UUIDの短縮形）
        unique_code = str(uuid.uuid4())[:8] 
        
        # 既存のレコードを UPDATE
        connection.execute(
            sa.update(supporter_table)
            .where(supporter_table.c.id == supporter_id)
            .values(staff_code=unique_code)
        )

    # ### 3. 制約を NOT NULL に変更する (最終的な確定) ###
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.alter_column('staff_code', existing_type=sa.String(length=20), nullable=False)
        # Unique制約もここで再度追加（モデル定義に沿って）
        batch_op.create_unique_constraint("uq_supporters_staff_code", ["staff_code"])


    # ### 4. 他のカラム (linked_plan_idなど) の処理をここに追記する ###
    # linked_plan_id は nullable=True のため、そのまま追加してOKです。
    with op.batch_alter_table('absence_response_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_plan_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_absence_response_logs_linked_plan_id'), ['linked_plan_id'], unique=False)
        batch_op.create_foreign_key(None, 'support_plans', ['linked_plan_id'], ['id'])

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('external_location_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporters_staff_code'))
        batch_op.drop_column('staff_code')

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_column('external_location_detail')
        batch_op.drop_column('location_type')

    with op.batch_alter_table('absence_response_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_absence_response_logs_linked_plan_id'))
        batch_op.drop_column('linked_plan_id')

    # ### end Alembic commands ###
