"""Add DECRYPT DATA

Revision ID: 0921aa0302b7
Revises: 501832410af0
Create Date: 2025-11-12 18:58:07.141567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0921aa0302b7'
down_revision = '501832410af0'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. NOT NULL制約を解除 (nullable=Trueに戻す)
    # 削除するカラムに残っている制約を事前に緩める。
    op.alter_column('specific_goals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema=None)
    
    # 2. user_id カラムを削除 (upgradeで追加したカラムを元に戻す)
    # Alembicが自動で外部キー制約を削除しない場合、op.drop_constraint()が必要になることがあります。
    op.drop_column('specific_goals', 'user_id')
    # ### end Alembic commands ###
