"""Re_add_missing_auth_and_billing_columns

Revision ID: 0ebe15524b89
Revises: 
Create Date: 2025-10-26 17:23:07.291074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ebe15524b89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_records')
    op.drop_table('comments')
    op.drop_table('employments')
    op.drop_table('government_offices')
    op.drop_table('contacts')
    op.drop_table('service_location_master')
    op.drop_table('assessments')
    op.drop_table('preparation_activity_master')
    op.drop_table('contracts_certificates')
    op.drop_table('monitorings')
    with op.batch_alter_table('attendance_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_planned', sa.Boolean(), nullable=True))
        batch_op.drop_column('planned_check_out')
        batch_op.drop_column('planned_check_in')
        batch_op.drop_column('remarks')
        batch_op.drop_column('is_recurring')

    with op.batch_alter_table('meeting_minutes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants', sa.Text(), nullable=True))
        batch_op.alter_column('meeting_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
        batch_op.drop_column('remarks')
        batch_op.drop_column('attendees')
        batch_op.drop_column('decisions')

    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_contact_date', sa.Date(), nullable=True))
        batch_op.drop_column('inquiry_date')
        batch_op.drop_column('last_name_kana')
        batch_op.drop_column('first_name_kana')

    with op.batch_alter_table('service_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('unit_time')

    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('remarks')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('birth_date')
        batch_op.drop_column('first_name_kana')
        batch_op.drop_column('address')
        batch_op.drop_column('remarks')
        batch_op.drop_column('phone')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('last_name_kana')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name_kana', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name_kana', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('service_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_time', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name_kana', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name_kana', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inquiry_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('initial_contact_date')

    with op.batch_alter_table('meeting_minutes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decisions', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attendees', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('meeting_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('participants')

    with op.batch_alter_table('attendance_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planned_check_in', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planned_check_out', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.drop_column('is_planned')

    op.create_table('monitorings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sabikan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monitoring_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('progress_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('evaluation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('monitorings_pkey'))
    )
    op.create_table('contracts_certificates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('certificate_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('max_burden_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supply_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contracts_certificates_pkey'))
    )
    op.create_table('preparation_activity_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('is_billable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('preparation_activity_master_pkey')),
    sa.UniqueConstraint('activity_name', name=op.f('preparation_activity_master_activity_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sabikan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('assessments_pkey'))
    )
    op.create_table('service_location_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_offsite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('service_location_master_pkey')),
    sa.UniqueConstraint('location_name', name=op.f('service_location_master_location_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contacts_pkey'))
    )
    op.create_table('government_offices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('municipality_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('municipality_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('government_offices_pkey'))
    )
    op.create_table('employments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_person_kana', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('employment_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_style_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disclosure_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employments_pkey'))
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('support_plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supporter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('check_out_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_billed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by_supporter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_supporter_id'], ['supporters.id'], name=op.f('attendance_records_created_by_supporter_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['attendance_status_master.id'], name=op.f('attendance_records_status_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_records_pkey')),
    sa.UniqueConstraint('user_id', 'record_date', name=op.f('_user_record_date_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
