"""add_user_schedule_and_request_tables

Revision ID: 218388db7269
Revises: 6fe30bb410e4
Create Date: 2026-06-08 13:06:56.817263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218388db7269'
down_revision = '6fe30bb410e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_schedule_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('requested_start_time', sa.String(length=5), nullable=True),
    sa.Column('requested_end_time', sa.String(length=5), nullable=True),
    sa.Column('request_reason', sa.Text(), nullable=False),
    sa.Column('request_status', sa.String(length=30), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_supporter_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_supporter_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['requested_by_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_schedule_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_schedule_requests_target_date'), ['target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_schedule_requests_user_id'), ['user_id'], unique=False)

    op.create_table('user_schedule_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', name='_user_day_template_uc')
    )
    with op.batch_alter_table('user_schedule_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_schedule_templates_user_id'), ['user_id'], unique=False)

    op.create_table('user_daily_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_status', sa.String(length=30), nullable=False),
    sa.Column('schedule_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_request_id'], ['user_schedule_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='_user_daily_schedule_uc')
    )
    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_schedules_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_daily_schedules_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_schedules_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_daily_schedules_date'))

    op.drop_table('user_daily_schedules')
    with op.batch_alter_table('user_schedule_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_schedule_templates_user_id'))

    op.drop_table('user_schedule_templates')
    with op.batch_alter_table('user_schedule_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_schedule_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_schedule_requests_target_date'))

    op.drop_table('user_schedule_requests')
    # ### end Alembic commands ###
