"""Add phase 2a staffing calculation models

Revision ID: 26b7aa0c1fd1
Revises: 90866e1d52b9
Create Date: 2026-07-19 09:41:00.386896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b7aa0c1fd1'
down_revision = '90866e1d52b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffing_calculation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', name='uq_staffing_calculation_rule_code'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from <= effective_to', name='chk_rule_effective_dates')
    )
    op.create_table('integrated_service_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=200), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_supporter_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_document_url', sa.String(length=2048), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from <= effective_to', name='chk_integrated_operation_effective_dates')
    )
    with op.batch_alter_table('integrated_service_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrated_service_operations_corporation_id'), ['corporation_id'], unique=False)

    op.create_table('integrated_service_operation_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integrated_service_operation_id', sa.Integer(), nullable=False),
    sa.Column('office_service_configuration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integrated_service_operation_id'], ['integrated_service_operations.id'], ),
    sa.ForeignKeyConstraint(['office_service_configuration_id'], ['office_service_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integrated_service_operation_id', 'office_service_configuration_id', name='uq_integrated_operation_member')
    )
    with op.batch_alter_table('integrated_service_operation_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrated_service_operation_members_integrated_service_operation_id'), ['integrated_service_operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrated_service_operation_members_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)

    op.create_table('staffing_calculation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_service_configuration_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('calculation_basis', sa.Text(), nullable=True),
    sa.Column('rule_snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['office_service_configuration_id'], ['office_service_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('period_start <= period_end', name='chk_run_period_dates')
    )
    with op.batch_alter_table('staffing_calculation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staffing_calculation_runs_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)

    op.create_table('staffing_calculation_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staffing_calculation_rule_id', sa.Integer(), nullable=False),
    sa.Column('source_assignment_id', sa.Integer(), nullable=False),
    sa.Column('target_assignment_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_supporter_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('no_service_disruption_confirmed', sa.Boolean(), nullable=False),
    sa.Column('no_service_disruption_confirmed_by_supporter_id', sa.Integer(), nullable=True),
    sa.Column('no_service_disruption_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('no_service_disruption_reason', sa.Text(), nullable=True),
    sa.Column('evidence_document_url', sa.String(length=2048), nullable=True),
    sa.Column('revoked_by_supporter_id', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['no_service_disruption_confirmed_by_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['source_assignment_id'], ['supporter_job_assignments.id'], ),
    sa.ForeignKeyConstraint(['staffing_calculation_rule_id'], ['staffing_calculation_rules.id'], ),
    sa.ForeignKeyConstraint(['target_assignment_id'], ['supporter_job_assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('source_assignment_id != target_assignment_id', name='chk_source_neq_target_assignment'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from <= effective_to', name='chk_exception_effective_dates')
    )
    op.create_table('staffing_calculation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staffing_calculation_run_id', sa.Integer(), nullable=False),
    sa.Column('supporter_job_assignment_id', sa.Integer(), nullable=False),
    sa.Column('ordinary_minutes', sa.Integer(), nullable=False),
    sa.Column('exception_minutes', sa.Integer(), nullable=False),
    sa.Column('total_counted_minutes', sa.Integer(), nullable=False),
    sa.Column('full_time_required_minutes', sa.Integer(), nullable=False),
    sa.Column('fte_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['staffing_calculation_run_id'], ['staffing_calculation_runs.id'], ),
    sa.ForeignKeyConstraint(['supporter_job_assignment_id'], ['supporter_job_assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('ordinary_minutes >= 0', name='chk_result_ordinary_minutes_positive'),
    sa.CheckConstraint('exception_minutes >= 0', name='chk_result_exception_minutes_positive'),
    sa.CheckConstraint('total_counted_minutes >= 0', name='chk_result_total_minutes_positive'),
    sa.CheckConstraint('full_time_required_minutes > 0', name='chk_result_ft_required_minutes_positive'),
    sa.CheckConstraint('fte_value >= 0', name='chk_result_fte_positive')
    )
    with op.batch_alter_table('staffing_calculation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staffing_calculation_results_staffing_calculation_run_id'), ['staffing_calculation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staffing_calculation_results_supporter_job_assignment_id'), ['supporter_job_assignment_id'], unique=False)

    op.create_table('staffing_calculation_result_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staffing_calculation_result_id', sa.Integer(), nullable=False),
    sa.Column('staffing_calculation_exception_id', sa.Integer(), nullable=False),
    sa.Column('applied_rule_code', sa.String(length=50), nullable=False),
    sa.Column('applied_rule_name', sa.String(length=200), nullable=False),
    sa.Column('applied_legal_basis', sa.Text(), nullable=True),
    sa.Column('rule_effective_from', sa.Date(), nullable=False),
    sa.Column('rule_effective_to', sa.Date(), nullable=True),
    sa.Column('added_minutes', sa.Integer(), nullable=False),
    sa.Column('source_assignment_id', sa.Integer(), nullable=False),
    sa.Column('target_assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_assignment_id'], ['supporter_job_assignments.id'], ),
    sa.ForeignKeyConstraint(['staffing_calculation_result_id'], ['staffing_calculation_results.id'], ),
    sa.ForeignKeyConstraint(['staffing_calculation_exception_id'], ['staffing_calculation_exceptions.id'], ),
    sa.ForeignKeyConstraint(['target_assignment_id'], ['supporter_job_assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('added_minutes >= 0', name='chk_result_exception_added_minutes_positive'),
    sa.CheckConstraint('rule_effective_to IS NULL OR rule_effective_from <= rule_effective_to', name='chk_result_exception_effective_dates')
    )
    with op.batch_alter_table('staffing_calculation_result_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staffing_calculation_result_exceptions_staffing_calculation_exception_id'), ['staffing_calculation_exception_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staffing_calculation_result_exceptions_staffing_calculation_result_id'), ['staffing_calculation_result_id'], unique=False)

    with op.batch_alter_table('staff_activity_allocation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporter_timecard_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('office_service_configuration_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_title_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allocation_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allocation_recording_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('allocated_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allocation_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('allocation_end_time', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_staff_activity_allocation_logs_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_activity_allocation_logs_supporter_timecard_id'), ['supporter_timecard_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_staff_activity_allocation_logs_job_title_id'), 'job_title_master', ['job_title_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_staff_activity_allocation_logs_office_service_config_id'), 'office_service_configurations', ['office_service_configuration_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_staff_activity_allocation_logs_supporter_timecard_id'), 'supporter_timecards', ['supporter_timecard_id'], ['id'])
        batch_op.create_check_constraint('chk_allocated_minutes_positive', 'allocated_minutes IS NULL OR allocated_minutes >= 0')

    with op.batch_alter_table('supporter_job_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_assigned_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assignment_mode', sa.String(length=20), nullable=True))
        batch_op.create_check_constraint('chk_weekly_assigned_minutes_positive', 'weekly_assigned_minutes IS NULL OR weekly_assigned_minutes >= 0')

    with op.batch_alter_table('supporter_timecards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sequence_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location_detail', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_supporter_timecards_office_id'), ['office_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('supporter_timecards_office_id_fkey'), 'office_settings', ['office_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporter_timecards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('supporter_timecards_office_id_fkey'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_supporter_timecards_office_id'))
        batch_op.drop_column('location_detail')
        batch_op.drop_column('location_type')
        batch_op.drop_column('sequence_no')
        batch_op.drop_column('office_id')

    with op.batch_alter_table('supporter_job_assignments', schema=None) as batch_op:
        batch_op.drop_column('assignment_mode')
        batch_op.drop_column('weekly_assigned_minutes')

    with op.batch_alter_table('staff_activity_allocation_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_staff_activity_allocation_logs_job_title_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_staff_activity_allocation_logs_office_service_config_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_staff_activity_allocation_logs_supporter_timecard_id'), type_='foreignkey')
        batch_op.drop_constraint('chk_allocated_minutes_positive', type_='check')
        batch_op.drop_index(batch_op.f('ix_staff_activity_allocation_logs_supporter_timecard_id'))
        batch_op.drop_index(batch_op.f('ix_staff_activity_allocation_logs_office_service_configuration_id'))
        batch_op.drop_column('allocation_end_time')
        batch_op.drop_column('allocation_start_time')
        batch_op.drop_column('allocated_minutes')
        batch_op.drop_column('allocation_recording_mode')
        batch_op.drop_column('allocation_type')
        batch_op.drop_column('job_title_id')
        batch_op.drop_column('office_service_configuration_id')
        batch_op.drop_column('supporter_timecard_id')

    with op.batch_alter_table('staffing_calculation_result_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staffing_calculation_result_exceptions_staffing_calculation_result_id'))
        batch_op.drop_index(batch_op.f('ix_staffing_calculation_result_exceptions_staffing_calculation_exception_id'))

    op.drop_table('staffing_calculation_result_exceptions')
    with op.batch_alter_table('staffing_calculation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staffing_calculation_results_supporter_job_assignment_id'))
        batch_op.drop_index(batch_op.f('ix_staffing_calculation_results_staffing_calculation_run_id'))

    op.drop_table('staffing_calculation_results')
    op.drop_table('staffing_calculation_exceptions')
    with op.batch_alter_table('staffing_calculation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staffing_calculation_runs_office_service_configuration_id'))

    op.drop_table('staffing_calculation_runs')
    with op.batch_alter_table('integrated_service_operation_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrated_service_operation_members_office_service_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_integrated_service_operation_members_integrated_service_operation_id'))

    op.drop_table('integrated_service_operation_members')
    with op.batch_alter_table('integrated_service_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrated_service_operations_corporation_id'))

    op.drop_table('integrated_service_operations')
    op.drop_table('staffing_calculation_rules')
    # ### end Alembic commands ###
