"""V1.0 全モデル反映

Revision ID: 2a725badd20a
Revises: a80c3fe9678f
Create Date: 2025-11-05 21:26:16.878741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a725badd20a'
down_revision = 'a80c3fe9678f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_source', sa.String(length=50), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('min_frequency', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('corporations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_name', sa.String(length=150), nullable=False),
    sa.Column('corporation_type', sa.String(length=50), nullable=False),
    sa.Column('representative_name', sa.String(length=100), nullable=True),
    sa.Column('corporation_number', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_number')
    )
    op.create_table('expense_category_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.text('true')), # ★ 修正 (nullable=Trueだが念のため)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fee_payer_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.text('true')), # ★ 修正 (nullable=Trueだが念のため)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('government_fee_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=False),
    sa.Column('disability_classification', sa.String(length=10), nullable=True),
    sa.Column('staff_ratio', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('eligibility_summary', sa.Text(), nullable=True),
    sa.Column('rule_document_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_code')
    )
    op.create_table('fee_eligibility_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_master_id', sa.Integer(), nullable=False),
    sa.Column('compliance_rule_id', sa.Integer(), nullable=True),
    sa.Column('requirement_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('reference_model', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['compliance_rule_id'], ['compliance_rules.id'], ),
    sa.ForeignKeyConstraint(['fee_master_id'], ['government_fee_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_contact_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('contact_date', sa.DateTime(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('contact_method', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_lead_generated', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.Column('acceptance_score', sa.Integer(), nullable=True),
    sa.Column('is_sustainable_partner', sa.Boolean(), nullable=True),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.Column('approval_supporter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category_master.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('work_location', sa.String(length=200), nullable=False),
    sa.Column('salary_type', sa.String(length=20), nullable=True),
    sa.Column('salary_amount', sa.Integer(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('suitable_user_profiles', sa.Text(), nullable=True),
    sa.Column('is_matched', sa.Boolean(), nullable=True, server_default=sa.text('false')), # ★ 修正 (nullable=Trueだが念のため)
    sa.Column('is_disabled_friendly', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_supporter_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contact_supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_outreach_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_date', sa.DateTime(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('target_institution', sa.String(length=200), nullable=False),
    sa.Column('contact_method', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_referral_generated', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('office_name', sa.String(length=100), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('owner_supporter_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality_master.id'], ),
    sa.ForeignKeyConstraint(['owner_supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_enrollment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('contact_date', sa.DateTime(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('initial_assessment_memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.Column('creator_supporter_id', sa.Integer(), nullable=False),
    sa.Column('is_canceled', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.ForeignKeyConstraint(['creator_supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supporter_timecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=False, server_default=sa.text('0')), # ★ 修正
    sa.Column('actual_work_minutes', sa.Integer(), nullable=False, server_default=sa.text('0')), # ★ 修正
    sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reporting_month', sa.Date(), nullable=False),
    sa.Column('total_days_attended', sa.Integer(), nullable=False, server_default=sa.text('0')), # ★ 修正
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False, server_default=sa.text('0')), # ★ 修正
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reporting_month', name='uq_user_month')
    )
    op.create_table('beneficiary_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=30), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('billing_municipality_id', sa.Integer(), nullable=False),
    sa.Column('contract_office_number', sa.String(length=20), nullable=False),
    sa.Column('disability_classification', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['billing_municipality_id'], ['municipality_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.ForeignKeyConstraint(['recipient_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fee_master_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('check_result_code', sa.String(length=50), nullable=False),
    sa.Column('is_satisfied', sa.Boolean(), nullable=False),
    sa.Column('feedback_message', sa.Text(), nullable=True),
    sa.Column('reference_model', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fee_master_id'], ['government_fee_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_support_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('actual_work_minutes', sa.Integer(), nullable=False),
    sa.Column('support_location', sa.String(length=100), nullable=False),
    sa.Column('support_content', sa.Text(), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_calculation_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('fee_master_id', sa.Integer(), nullable=False),
    sa.Column('calculation_month', sa.Date(), nullable=False),
    sa.Column('is_calculated', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('decision_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fee_master_id'], ['government_fee_master.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_retention_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_office_number', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.Column('fee_payer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fee_payer_id'], ['fee_payer_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_type', sa.String(length=50), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('visit_frequency', sa.String(length=50), nullable=True),
    sa.Column('medication_details', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office_additive_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('fee_master_id', sa.Integer(), nullable=False),
    sa.Column('is_filed', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['fee_master_id'], ['government_fee_master.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office_service_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('service_provider_number', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_enrollment_assessment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_item_master.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['pre_enrollment_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supporter_id', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'参加予定'")), # ★ 修正
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('service_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('service_content', sa.Text(), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=False),
    sa.Column('break_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copayment_limit_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('copayment_limit', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['beneficiary_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_retention_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('support_method', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('support_content', sa.Text(), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False, server_default=sa.text('true')), # ★ 修正
    sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.ForeignKeyConstraint(['contract_id'], ['job_retention_contracts.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provisional_service_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['beneficiary_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readiness_assessment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=True),
    sa.Column('supporter_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_item_master.id'], ),
    sa.ForeignKeyConstraint(['score_id'], ['assessment_score_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_supporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=True),
    sa.Column('external_record_id', sa.Integer(), nullable=True),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.text('false')), # ★ 修正
    sa.ForeignKeyConstraint(['external_record_id'], ['external_support_records.id'], ),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_provision_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['beneficiary_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_record_additives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=True),
    sa.Column('external_record_id', sa.Integer(), nullable=True),
    sa.Column('fee_master_id', sa.Integer(), nullable=False),
    sa.Column('units_applied', sa.Numeric(), nullable=False),
    sa.Column('fee_rate_at_record', sa.Numeric(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['external_record_id'], ['external_support_records.id'], ),
    sa.ForeignKeyConstraint(['fee_master_id'], ['government_fee_master.id'], ),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_unit_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('daily_units_per_month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['beneficiary_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # --- ★ ここからが修正対象の BATCH ALTER TABLE と DROP TABLE です ★ ---
    
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualifications_user_id'))

    op.drop_table('qualifications')
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_user_id'))

    op.drop_table('family_members')
    with op.batch_alter_table('developmental_history_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developmental_history_items_event_period'))
        batch_op.drop_index(batch_op.f('ix_developmental_history_items_user_id'))

    # ★ 修正: 順番を入れ替え。子(association)を先に削除
    op.drop_table('developmental_history_categories_association')
    
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        # ★ 修正: server_default を追加 (NOT NULL 制約エラー回避)
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False, server_default=sa.text("'不明'")))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        # ★ 修正: server_default を追加 (NOT NULL 制約エラー回避)
        batch_op.alter_column('relationship',
                              existing_type=sa.VARCHAR(length=50),
                              nullable=False,
                              server_default=sa.text("'不明'"))
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_priority'))
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_user_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('address')
        batch_op.drop_column('name')
        batch_op.drop_column('priority')
        batch_op.drop_column('remarks')

    # ★ 修正: 順番を入れ替え。親(items)を後で削除
    op.drop_table('developmental_history_items')
    
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_certificates_user_id'))

    op.drop_table('certificates')
    
    # ★ 修正: ここがエラーの直接の原因 (supporters)
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_full_time', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('scheduled_work_hours', sa.Integer(), nullable=False, server_default=sa.text('40')))
        batch_op.add_column(sa.Column('employment_type', sa.String(length=50), nullable=False, server_default=sa.text("'正社員'")))

    # ★ 修正: ここもエラーになるため予防 (users)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('service_end_date', sa.Date(), nullable=True))
        # ★ 修正: nullable=False と server_default をモデル定義に合わせる
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('is_archivable', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        # ★ 修正: nullable=False と server_default をモデル定義に合わせる (Alembicの誤検知)
        batch_op.add_column(sa.Column('remote_service_allowed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('plan_consultation_office', sa.String(length=100), nullable=True))
        # ★ 修正: nullable=False と server_default をモデル定義に合わせる
        batch_op.add_column(sa.Column('is_currently_working', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('employment_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('handbook_level', sa.String(length=20), nullable=True))
        # ★ 修正: nullable=False と server_default をモデル定義に合わせる (Alembicの誤検CH)
        batch_op.add_column(sa.Column('is_handbook_certified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.alter_column('status_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name_kana'))
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_last_name_kana'))
        batch_op.drop_index(batch_op.f('ix_users_primary_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_users_start_date'))
        batch_op.drop_index(batch_op.f('ix_users_status_id'))
        batch_op.drop_constraint(batch_op.f('users_gender_legal_id_fkey'), type_='foreignkey')
        batch_op.drop_column('gender_identity')
        batch_op.drop_column('start_date')
        batch_op.drop_column('support_needs')
        batch_op.drop_column('disability_details')
        batch_op.drop_column('end_date')
        batch_op.drop_column('gender_legal_id')

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_legal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('disability_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('support_needs', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender_identity', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_gender_legal_id_fkey'), 'gender_legal_master', ['gender_legal_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_users_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_primary_supporter_id'), ['primary_supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name_kana'), ['last_name_kana'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_first_name_kana'), ['first_name_kana'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_handbook_certified')
        batch_op.drop_column('handbook_level')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('employment_start_date')
        batch_op.drop_column('is_currently_working')
        batch_op.drop_column('plan_consultation_office')
        batch_op.drop_column('remote_service_allowed')
        batch_op.drop_column('is_archivable')
        batch_op.drop_column('is_active')
        batch_op.drop_column('service_end_date')
        batch_op.drop_column('service_start_date')

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.drop_column('employment_type')
        batch_op.drop_column('scheduled_work_hours')
        batch_op.drop_column('is_full_time')

    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_emergency_contacts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_contacts_priority'), ['priority'], unique=False)
        batch_op.alter_column('relationship',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('note')
        batch_op.drop_column('full_name')

    op.create_table('developmental_history_categories_association',
    sa.Column('history_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['history_category_master.id'], name=op.f('developmental_history_categories_association_category_id_fkey')),
    sa.ForeignKeyConstraint(['history_item_id'], ['developmental_history_items.id'], name=op.f('developmental_history_categories_associati_history_item_id_fkey')),
    sa.PrimaryKeyConstraint('history_item_id', 'category_id', name=op.f('developmental_history_categories_association_pkey'))
    )
    op.create_table('certificates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificate_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certificate_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('billing_municipality_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('copayment_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('copayment_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('copayment_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('service_amount', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('service_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ramp_service_field_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ramp_service_amount', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ramp_contract_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ramp_contract_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['billing_municipality_id'], ['municipality_master.id'], name=op.f('certificates_billing_municipality_id_fkey')),
    sa.ForeignKeyConstraint(['certificate_type_id'], ['certificate_type_master.id'], name=op.f('certificates_certificate_type_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('certificates_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certificates_pkey'))
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_expiry_date'), ['expiry_date'], unique=False)

    op.create_table('developmental_history_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_period', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('developmental_history_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('developmental_history_items_pkey'))
    )
    with op.batch_alter_table('developmental_history_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developmental_history_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_developmental_history_items_event_period'), ['event_period'], unique=False)

    op.create_table('family_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_living_together', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('health_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('family_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('family_members_pkey'))
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_user_id'), ['user_id'], unique=False)

    op.create_table('qualifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualification_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('acquisition_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('issuing_organization', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('qualifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('qualifications_pkey'))
    )
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualifications_user_id'), ['user_id'], unique=False)

    op.drop_table('service_unit_periods')
    op.drop_table('service_record_additives')
    op.drop_table('service_provision_periods')
    op.drop_table('record_supporters')
    op.drop_table('readiness_assessment_results')
    op.drop_table('provisional_service_periods')
    op.drop_table('job_retention_records')
    op.drop_table('copayment_limit_periods')
    op.drop_table('break_records')
    op.drop_table('service_records')
    op.drop_table('schedule_participants')
    op.drop_table('pre_enrollment_assessment_scores')
    op.drop_table('office_service_configurations')
    op.drop_table('office_additive_filings')
    op.drop_table('medical_institutions')
    op.drop_table('job_retention_contracts')
    op.drop_table('fee_calculation_decisions')
    op.drop_table('external_support_records')
    op.drop_table('compliance_facts')
    op.drop_table('chat_messages')
    op.drop_table('beneficiary_certificates')
    op.drop_table('attendance_records')
    op.drop_table('supporter_timecards')
    op.drop_table('schedules')
    op.drop_table('pre_enrollment_logs')
    op.drop_table('office_settings')
    op.drop_table('marketing_outreach_logs')
    op.drop_table('job_offers')
    op.drop_table('expense_records')
    op.drop_table('company_contact_logs')
    op.drop_table('fee_eligibility_requirements')
    op.drop_table('government_fee_master')
    op.drop_table('fee_payer_master')
    op.drop_table('expense_category_master')
    op.drop_table('corporations')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
