"""add_job_title_permission_link

Revision ID: 2b9f67e27f16
Revises: a69a16b6b100
Create Date: 2026-06-08 12:38:48.244553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9f67e27f16'
down_revision = 'a69a16b6b100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_title_permission_link',
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title_master.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission_master.id'], ),
    sa.PrimaryKeyConstraint('job_title_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_title_permission_link')
    # ### end Alembic commands ###
