"""V2.0 - Initial logical model structure

Revision ID: 2c5f03c019a9
Revises: 
Create Date: 2025-11-17 20:15:46.224617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5f03c019a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessor_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('committee_type_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('required_frequency_months', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_name', sa.String(length=150), nullable=False),
    sa.Column('corporation_type', sa.String(length=50), nullable=False),
    sa.Column('representative_name', sa.String(length=100), nullable=True),
    sa.Column('corporation_number', sa.String(length=20), nullable=True),
    sa.Column('establishment_date', sa.Date(), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('corporation_seal_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corporation_number')
    )
    op.create_table('disability_type_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_type_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employer_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry_type', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employer_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employer_master_company_name'), ['company_name'], unique=False)

    op.create_table('gender_legal_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_title_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_name', sa.String(length=100), nullable=False),
    sa.Column('is_management_role', sa.Boolean(), nullable=True),
    sa.Column('is_qualified_role', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_name')
    )
    op.create_table('municipality_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_code')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('main_phone', sa.String(length=20), nullable=True),
    sa.Column('main_email', sa.String(length=120), nullable=True),
    sa.Column('main_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_organization_name'), ['organization_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_organization_type'), ['organization_type'], unique=False)

    op.create_table('permission_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('standard_wage_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualification_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_legal_mandate', sa.Boolean(), nullable=True),
    sa.Column('specialty_domain', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role_scope', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('schedule_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_start_time'), ['start_time'], unique=False)

    op.create_table('service_type_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('service_code', sa.String(length=20), nullable=False),
    sa.Column('required_review_months', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_code')
    )
    op.create_table('skill_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_activity_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name_kana', sa.String(length=50), nullable=False),
    sa.Column('first_name_kana', sa.String(length=50), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('weekly_scheduled_minutes', sa.Integer(), nullable=False),
    sa.Column('employment_contract_url', sa.String(length=500), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supporters_email'), ['email'], unique=True)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry_type', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessor_type_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=True),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessor_type_id'], ['assessor_types.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_assessments_goal_id'), ['goal_id'], unique=False)

    op.create_table('job_development_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employer_master.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_development_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_development_logs_employer_id'), ['employer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_development_logs_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('office_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('office_name', sa.String(length=100), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('office_seal_image_url', sa.String(length=500), nullable=True),
    sa.Column('full_time_weekly_minutes', sa.Integer(), nullable=False),
    sa.Column('local_rules_config', sa.JSON(), nullable=True),
    sa.Column('bcp_document_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('office_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_settings_corporation_id'), ['corporation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_office_settings_municipality_id'), ['municipality_id'], unique=False)

    op.create_table('role_permission_link',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission_master.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role_master.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('staff_reflection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('reflection_timestamp', sa.DateTime(), nullable=False),
    sa.Column('context_log_type', sa.String(length=50), nullable=True),
    sa.Column('context_log_id', sa.Integer(), nullable=True),
    sa.Column('reflection_summary', sa.Text(), nullable=False),
    sa.Column('personal_growth_plan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_reflection_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_reflection_logs_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('supporter_attendance_correction_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('requested_timestamp', sa.DateTime(), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=False),
    sa.Column('request_status', sa.String(length=20), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supporter_attendance_correction_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supporter_attendance_correction_requests_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('supporter_qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('qualification_master_id', sa.Integer(), nullable=False),
    sa.Column('certification_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('certificate_document_url', sa.String(length=500), nullable=True),
    sa.Column('training_evaluation_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qualification_master_id'], ['qualification_master.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supporter_qualifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supporter_qualifications_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('supporter_role_link',
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role_master.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('supporter_id', 'role_id')
    )
    op.create_table('training_prerequisite_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=True),
    sa.Column('law_name', sa.String(length=100), nullable=True),
    sa.Column('law_article', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('primary_supporter_id', sa.Integer(), nullable=True),
    sa.Column('service_start_date', sa.Date(), nullable=True),
    sa.Column('service_end_date', sa.Date(), nullable=True),
    sa.Column('is_return_to_work_case', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['primary_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_primary_supporter_id'), ['primary_supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_service_start_date'), ['service_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status_id'), ['status_id'], unique=False)

    op.create_table('acquisition_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=True),
    sa.Column('prospect_user_id', sa.Integer(), nullable=True),
    sa.Column('activity_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['prospect_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acquisition_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acquisition_activity_logs_prospect_user_id'), ['prospect_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_activity_logs_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location_data', sa.String(length=255), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_user_id'), ['user_id'], unique=False)

    op.create_table('audit_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supporter_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('change_details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_action_logs_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_action_logs_user_id'), ['user_id'], unique=False)

    op.create_table('client_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('self_pay_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_cost_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('invoice_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('receipt_confirmation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('handover_method', sa.String(length=30), nullable=True),
    sa.Column('handover_supporter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handover_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['payment_confirmed_by_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_invoices_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_invoices_user_id'), ['user_id'], unique=False)

    op.create_table('committee_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('committee_type_id', sa.Integer(), nullable=False),
    sa.Column('meeting_timestamp', sa.DateTime(), nullable=False),
    sa.Column('discussion_summary', sa.Text(), nullable=False),
    sa.Column('decided_action_plan', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_type_id'], ['committee_type_master.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('committee_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committee_activity_logs_committee_type_id'), ['committee_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_activity_logs_office_id'), ['office_id'], unique=False)

    op.create_table('complaint_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complainant_user_id', sa.Integer(), nullable=True),
    sa.Column('complainant_name', sa.String(length=100), nullable=True),
    sa.Column('complainant_type', sa.String(length=50), nullable=False),
    sa.Column('reception_timestamp', sa.DateTime(), nullable=False),
    sa.Column('complaint_summary', sa.Text(), nullable=False),
    sa.Column('investigation_details', sa.Text(), nullable=True),
    sa.Column('resolution_action_taken', sa.Text(), nullable=True),
    sa.Column('complaint_status', sa.String(length=30), nullable=False),
    sa.Column('closure_timestamp', sa.DateTime(), nullable=True),
    sa.Column('responsible_supporter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complainant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_logs_complainant_user_id'), ['complainant_user_id'], unique=False)

    op.create_table('compliance_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_event_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_event_logs_user_id'), ['user_id'], unique=False)

    op.create_table('crisis_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('crisis_signs', sa.Text(), nullable=True),
    sa.Column('coping_strategies', sa.Text(), nullable=True),
    sa.Column('emergency_contacts_detail', sa.Text(), nullable=True),
    sa.Column('created_by_supporter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crisis_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crisis_plans_user_id'), ['user_id'], unique=False)

    op.create_table('document_consent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=False),
    sa.Column('consent_proof', sa.String(length=255), nullable=True),
    sa.Column('generated_document_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_consent_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_consent_logs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_consent_logs_user_id'), ['user_id'], unique=False)

    op.create_table('holistic_support_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('user_intention_content', sa.Text(), nullable=False),
    sa.Column('support_policy_content', sa.Text(), nullable=False),
    sa.Column('support_considerations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holistic_support_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holistic_support_policies_user_id'), ['user_id'], unique=False)

    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reporting_staff_id', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.String(length=30), nullable=False),
    sa.Column('occurrence_timestamp', sa.DateTime(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=False),
    sa.Column('cause_analysis', sa.Text(), nullable=False),
    sa.Column('preventive_action_plan', sa.Text(), nullable=False),
    sa.Column('report_status', sa.String(length=30), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['reporting_staff_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_reports_incident_type'), ['incident_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_reporting_staff_id'), ['reporting_staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_user_id'), ['user_id'], unique=False)

    op.create_table('job_placement_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('placement_date', sa.Date(), nullable=False),
    sa.Column('support_scenario', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('weekly_work_hours', sa.Integer(), nullable=True),
    sa.Column('follow_up_support_content', sa.Text(), nullable=True),
    sa.Column('separation_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employer_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_placement_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_placement_logs_employer_id'), ['employer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_placement_logs_user_id'), ['user_id'], unique=False)

    op.create_table('job_retention_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_start_date', sa.Date(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=False),
    sa.Column('contract_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_retention_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_retention_contracts_user_id'), ['user_id'], unique=False)

    op.create_table('monthly_attendance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_month', sa.Date(), nullable=False),
    sa.Column('planned_sessions', sa.Integer(), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('plan_status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_attendance_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_attendance_plans_target_month'), ['target_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_attendance_plans_user_id'), ['user_id'], unique=False)

    op.create_table('office_service_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('service_type_master_id', sa.Integer(), nullable=False),
    sa.Column('manager_supporter_id', sa.Integer(), nullable=True),
    sa.Column('jigyosho_bango', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('initial_designation_date', sa.Date(), nullable=True),
    sa.Column('operational_regulations_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['manager_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.ForeignKeyConstraint(['service_type_master_id'], ['service_type_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jigyosho_bango')
    )
    with op.batch_alter_table('office_service_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_service_configurations_manager_supporter_id'), ['manager_supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_office_service_configurations_office_id'), ['office_id'], unique=False)

    op.create_table('office_training_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('training_name', sa.String(length=255), nullable=False),
    sa.Column('training_type', sa.String(length=50), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('instructor', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('office_training_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_training_events_office_id'), ['office_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_office_training_events_training_type'), ['training_type'], unique=False)

    op.create_table('post_transition_follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('support_method', sa.String(length=50), nullable=False),
    sa.Column('support_details', sa.Text(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_transition_follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_transition_follow_ups_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_participants',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('schedule_id', 'user_id', 'supporter_id')
    )
    with op.batch_alter_table('schedule_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_participants_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_participants_user_id'), ['user_id'], unique=False)

    op.create_table('service_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certificate_issue_date', sa.Date(), nullable=False),
    sa.Column('municipality_master_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type', sa.String(length=50), nullable=True),
    sa.Column('disability_support_classification', sa.String(length=20), nullable=True),
    sa.Column('certificate_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_master_id'], ['municipality_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_certificates_municipality_master_id'), ['municipality_master_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_certificates_user_id'), ['user_id'], unique=False)

    op.create_table('support_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('plan_status', sa.String(length=30), nullable=False),
    sa.Column('sabikan_approved_by_id', sa.Integer(), nullable=True),
    sa.Column('sabikan_approved_at', sa.DateTime(), nullable=True),
    sa.Column('based_on_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['based_on_plan_id'], ['support_plans.id'], ),
    sa.ForeignKeyConstraint(['sabikan_approved_by_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_plans_user_id'), ['user_id'], unique=False)

    op.create_table('support_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_threads_user_id'), ['user_id'], unique=False)

    op.create_table('supporter_feedback_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('feedback_timestamp', sa.DateTime(), nullable=False),
    sa.Column('rating_score', sa.Integer(), nullable=True),
    sa.Column('narrative_feedback', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supporter_feedback_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supporter_feedback_logs_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supporter_feedback_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_attendance_correction_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('requested_timestamp', sa.DateTime(), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=False),
    sa.Column('request_status', sa.String(length=20), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_attendance_correction_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_attendance_correction_requests_user_id'), ['user_id'], unique=False)

    op.create_table('user_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type_master_id', sa.Integer(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('assessment_notes_by_staff', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_master_id'], ['document_type_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_documents_user_id'), ['user_id'], unique=False)

    op.create_table('user_organization_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('responsible_person_name', sa.String(length=100), nullable=True),
    sa.Column('link_start_date', sa.Date(), nullable=True),
    sa.Column('link_end_date', sa.Date(), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_organization_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_organization_links_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_organization_links_user_id'), ['user_id'], unique=False)

    op.create_table('user_pii',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name_kana', sa.String(length=50), nullable=True),
    sa.Column('first_name_kana', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender_legal_id', sa.Integer(), nullable=True),
    sa.Column('gender_identity', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.Column('sns_provider', sa.String(length=50), nullable=True),
    sa.Column('sns_account_id', sa.String(length=255), nullable=True),
    sa.Column('encrypted_certificate_number', sa.String(length=512), nullable=True),
    sa.Column('disability_type_id', sa.Integer(), nullable=True),
    sa.Column('disability_details', sa.Text(), nullable=True),
    sa.Column('support_needs', sa.Text(), nullable=True),
    sa.Column('handbook_level', sa.String(length=20), nullable=True),
    sa.Column('is_handbook_certified', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(sns_provider IS NULL AND sns_account_id IS NULL) OR (sns_provider IS NOT NULL AND sns_account_id IS NOT NULL)', name='ck_userpii_sns_auth_pair'),
    sa.ForeignKeyConstraint(['disability_type_id'], ['disability_type_master.id'], ),
    sa.ForeignKeyConstraint(['gender_legal_id'], ['gender_legal_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sns_provider', 'sns_account_id', name='uq_userpii_sns_auth'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_pii', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_pii_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_pii_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pii_first_name_kana'), ['first_name_kana'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pii_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pii_last_name_kana'), ['last_name_kana'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pii_sns_account_id'), ['sns_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pii_sns_provider'), ['sns_provider'], unique=False)

    op.create_table('user_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_requests_user_id'), ['user_id'], unique=False)

    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_master_id', sa.Integer(), nullable=False),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('training_evaluation_score', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['skill_master_id'], ['skill_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_skills_user_id'), ['user_id'], unique=False)

    op.create_table('user_wage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calculation_month', sa.Date(), nullable=False),
    sa.Column('total_work_minutes', sa.Integer(), nullable=True),
    sa.Column('total_units_passed', sa.Integer(), nullable=True),
    sa.Column('gross_wage_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_payment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_wage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_wage_logs_calculation_month'), ['calculation_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_wage_logs_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_supporter_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['support_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_sender_supporter_id'), ['sender_supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sender_user_id'), ['sender_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('copayment_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('limit_start_date', sa.Date(), nullable=False),
    sa.Column('limit_end_date', sa.Date(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['service_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copayment_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copayment_limits_certificate_id'), ['certificate_id'], unique=False)

    op.create_table('copayment_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('management_start_date', sa.Date(), nullable=False),
    sa.Column('management_end_date', sa.Date(), nullable=False),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('managing_office_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['service_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copayment_management', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copayment_management_certificate_id'), ['certificate_id'], unique=False)

    op.create_table('granted_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('granted_start_date', sa.Date(), nullable=False),
    sa.Column('granted_end_date', sa.Date(), nullable=False),
    sa.Column('granted_amount_description', sa.String(length=100), nullable=True),
    sa.Column('is_tentative', sa.Boolean(), nullable=False),
    sa.Column('tentative_start_date', sa.Date(), nullable=True),
    sa.Column('tentative_end_date', sa.Date(), nullable=True),
    sa.Column('service_type_master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['service_certificates.id'], ),
    sa.ForeignKeyConstraint(['service_type_master_id'], ['service_type_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('granted_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_granted_services_certificate_id'), ['certificate_id'], unique=False)

    op.create_table('job_retention_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('support_method', sa.String(length=50), nullable=False),
    sa.Column('support_details', sa.Text(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['job_retention_contracts.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_retention_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_retention_records_contract_id'), ['contract_id'], unique=False)

    op.create_table('long_term_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_period_start', sa.Date(), nullable=True),
    sa.Column('target_period_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['support_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('long_term_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_long_term_goals_plan_id'), ['plan_id'], unique=False)

    op.create_table('meal_addon_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('meal_addon_start_date', sa.Date(), nullable=False),
    sa.Column('meal_addon_end_date', sa.Date(), nullable=False),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['service_certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_addon_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_addon_statuses_certificate_id'), ['certificate_id'], unique=False)

    op.create_table('monitoring_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_plan_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('monitoring_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['support_plan_id'], ['support_plans.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_reports_support_plan_id'), ['support_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_reports_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('monthly_billing_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('office_service_configuration_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('total_units_claimed', sa.Integer(), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('claim_status', sa.String(length=30), nullable=False),
    sa.Column('lock_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_service_configuration_id'], ['office_service_configurations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_billing_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_billing_summary_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_billing_summary_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_billing_summary_user_id'), ['user_id'], unique=False)

    op.create_table('plan_review_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('support_plan_id', sa.Integer(), nullable=False),
    sa.Column('request_originator_type', sa.String(length=20), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=False),
    sa.Column('request_status', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['support_plan_id'], ['support_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_review_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_review_requests_support_plan_id'), ['support_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_review_requests_user_id'), ['user_id'], unique=False)

    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_service_configuration_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('invoice_status', sa.String(length=30), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['office_service_configuration_id'], ['office_service_configurations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoices_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('support_conference_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('conference_date', sa.DateTime(), nullable=False),
    sa.Column('participant_user_flag', sa.Boolean(), nullable=True),
    sa.Column('minutes_content', sa.Text(), nullable=True),
    sa.Column('is_charge_meeting', sa.Boolean(), nullable=True),
    sa.Column('external_participant_id', sa.Integer(), nullable=True),
    sa.Column('external_participant_signature_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['external_participant_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['support_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_conference_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_conference_logs_plan_id'), ['plan_id'], unique=False)

    op.create_table('supporter_job_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('office_service_configuration_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('assigned_minutes', sa.Integer(), nullable=False),
    sa.Column('is_deemed_assignment', sa.Boolean(), nullable=True),
    sa.Column('deemed_document_url', sa.String(length=500), nullable=True),
    sa.Column('deemed_expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title_master.id'], ),
    sa.ForeignKeyConstraint(['office_service_configuration_id'], ['office_service_configurations.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supporter_id', 'job_title_id', 'start_date', 'office_service_configuration_id', name='uq_supporter_job_assignment')
    )
    with op.batch_alter_table('supporter_job_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supporter_job_assignments_job_title_id'), ['job_title_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supporter_job_assignments_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supporter_job_assignments_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('supporter_timecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('office_service_configuration_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('total_break_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_work_minutes', sa.Integer(), nullable=False),
    sa.Column('is_absent', sa.Boolean(), nullable=True),
    sa.Column('absence_type', sa.String(length=50), nullable=True),
    sa.Column('deemed_work_minutes', sa.Integer(), nullable=True),
    sa.Column('facility_out_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['office_service_configuration_id'], ['office_service_configurations.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supporter_timecards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supporter_timecards_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supporter_timecards_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('training_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('office_training_event_id', sa.Integer(), nullable=True),
    sa.Column('training_name', sa.String(length=255), nullable=False),
    sa.Column('training_type', sa.String(length=50), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('summary_of_learning', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['office_training_event_id'], ['office_training_events.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_logs_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('agency_receipt_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('monthly_summary_id', sa.Integer(), nullable=False),
    sa.Column('kokuhoren_payment_date', sa.Date(), nullable=False),
    sa.Column('statement_pdf_url', sa.String(length=500), nullable=False),
    sa.Column('receipt_confirmation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('handover_method', sa.String(length=30), nullable=True),
    sa.Column('handover_supporter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handover_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['monthly_summary_id'], ['monthly_billing_summary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monthly_summary_id')
    )
    with op.batch_alter_table('agency_receipt_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agency_receipt_statements_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_agency_receipt_statements_user_id'), ['user_id'], unique=False)

    op.create_table('contract_report_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('granted_service_id', sa.Integer(), nullable=False),
    sa.Column('contract_corporation_name', sa.String(length=100), nullable=True),
    sa.Column('contract_office_name', sa.String(length=100), nullable=True),
    sa.Column('contract_service_type', sa.String(length=50), nullable=True),
    sa.Column('contract_granted_days', sa.Integer(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('contract_document_url', sa.String(length=500), nullable=True),
    sa.Column('important_matters_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['granted_service_id'], ['granted_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_report_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_report_details_granted_service_id'), ['granted_service_id'], unique=True)

    op.create_table('short_term_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_term_goal_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_period_start', sa.Date(), nullable=True),
    sa.Column('target_period_end', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['long_term_goal_id'], ['long_term_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('short_term_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_short_term_goals_long_term_goal_id'), ['long_term_goal_id'], unique=False)

    op.create_table('individual_support_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_term_goal_id', sa.Integer(), nullable=False),
    sa.Column('concrete_goal', sa.Text(), nullable=False),
    sa.Column('user_commitment', sa.Text(), nullable=False),
    sa.Column('support_actions', sa.Text(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('is_facility_in_deemed', sa.Boolean(), nullable=False),
    sa.Column('is_work_preparation_positioning', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['short_term_goal_id'], ['short_term_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('individual_support_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_individual_support_goals_short_term_goal_id'), ['short_term_goal_id'], unique=False)

    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('tardiness_minutes', sa.Integer(), nullable=True),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=True),
    sa.Column('work_preparation_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_score', sa.Integer(), nullable=True),
    sa.Column('physical_condition_score', sa.Integer(), nullable=True),
    sa.Column('grooming_check', sa.Boolean(), nullable=True),
    sa.Column('daily_goal_commitment', sa.Text(), nullable=True),
    sa.Column('user_self_evaluation', sa.Text(), nullable=True),
    sa.Column('user_lifestyle_notes', sa.Text(), nullable=True),
    sa.Column('support_content_notes', sa.Text(), nullable=False),
    sa.Column('log_status', sa.String(length=30), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['individual_support_goals.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_user_id'), ['user_id'], unique=False)

    op.create_table('absence_response_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('absence_date', sa.Date(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('response_timestamp', sa.DateTime(), nullable=True),
    sa.Column('response_supporter_id', sa.Integer(), nullable=False),
    sa.Column('response_method', sa.String(length=50), nullable=False),
    sa.Column('response_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.ForeignKeyConstraint(['response_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('daily_log_id')
    )
    with op.batch_alter_table('absence_response_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absence_response_logs_absence_date'), ['absence_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_absence_response_logs_user_id'), ['user_id'], unique=False)

    op.create_table('break_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=False),
    sa.Column('break_start_time', sa.DateTime(), nullable=False),
    sa.Column('break_end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('break_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_break_records_daily_log_id'), ['daily_log_id'], unique=False)

    op.create_table('daily_productivity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_log_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('units_passed_inspection', sa.Integer(), nullable=True),
    sa.Column('units_rejected', sa.Integer(), nullable=True),
    sa.Column('rejection_analysis_notes', sa.Text(), nullable=True),
    sa.Column('is_repaired', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_productivity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_productivity_logs_daily_log_id'), ['daily_log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_productivity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_productivity_logs_daily_log_id'))

    op.drop_table('daily_productivity_logs')
    with op.batch_alter_table('break_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_break_records_daily_log_id'))

    op.drop_table('break_records')
    with op.batch_alter_table('absence_response_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_response_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_absence_response_logs_absence_date'))

    op.drop_table('absence_response_logs')
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_goal_id'))

    op.drop_table('daily_logs')
    with op.batch_alter_table('individual_support_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individual_support_goals_short_term_goal_id'))

    op.drop_table('individual_support_goals')
    with op.batch_alter_table('short_term_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_term_goals_long_term_goal_id'))

    op.drop_table('short_term_goals')
    with op.batch_alter_table('contract_report_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_report_details_granted_service_id'))

    op.drop_table('contract_report_details')
    with op.batch_alter_table('agency_receipt_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agency_receipt_statements_user_id'))
        batch_op.drop_index(batch_op.f('ix_agency_receipt_statements_billing_month'))

    op.drop_table('agency_receipt_statements')
    with op.batch_alter_table('training_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_logs_supporter_id'))

    op.drop_table('training_logs')
    with op.batch_alter_table('supporter_timecards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporter_timecards_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_supporter_timecards_office_service_configuration_id'))

    op.drop_table('supporter_timecards')
    with op.batch_alter_table('supporter_job_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporter_job_assignments_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_supporter_job_assignments_office_service_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_supporter_job_assignments_job_title_id'))

    op.drop_table('supporter_job_assignments')
    with op.batch_alter_table('support_conference_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_conference_logs_plan_id'))

    op.drop_table('support_conference_logs')
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoices_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_office_service_configuration_id'))

    op.drop_table('sales_invoices')
    with op.batch_alter_table('plan_review_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_review_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_plan_review_requests_support_plan_id'))

    op.drop_table('plan_review_requests')
    with op.batch_alter_table('monthly_billing_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_billing_summary_user_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_billing_summary_office_service_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_billing_summary_billing_month'))

    op.drop_table('monthly_billing_summary')
    with op.batch_alter_table('monitoring_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_reports_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_reports_support_plan_id'))

    op.drop_table('monitoring_reports')
    with op.batch_alter_table('meal_addon_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_addon_statuses_certificate_id'))

    op.drop_table('meal_addon_statuses')
    with op.batch_alter_table('long_term_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_long_term_goals_plan_id'))

    op.drop_table('long_term_goals')
    with op.batch_alter_table('job_retention_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_retention_records_contract_id'))

    op.drop_table('job_retention_records')
    with op.batch_alter_table('granted_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_granted_services_certificate_id'))

    op.drop_table('granted_services')
    with op.batch_alter_table('copayment_management', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copayment_management_certificate_id'))

    op.drop_table('copayment_management')
    with op.batch_alter_table('copayment_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copayment_limits_certificate_id'))

    op.drop_table('copayment_limits')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_sender_supporter_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('user_wage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_wage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_wage_logs_calculation_month'))

    op.drop_table('user_wage_logs')
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skills_user_id'))

    op.drop_table('user_skills')
    with op.batch_alter_table('user_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_requests_user_id'))

    op.drop_table('user_requests')
    with op.batch_alter_table('user_pii', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_pii_sns_provider'))
        batch_op.drop_index(batch_op.f('ix_user_pii_sns_account_id'))
        batch_op.drop_index(batch_op.f('ix_user_pii_last_name_kana'))
        batch_op.drop_index(batch_op.f('ix_user_pii_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_pii_first_name_kana'))
        batch_op.drop_index(batch_op.f('ix_user_pii_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_pii_email'))

    op.drop_table('user_pii')
    with op.batch_alter_table('user_organization_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_organization_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_organization_links_organization_id'))

    op.drop_table('user_organization_links')
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_documents_user_id'))

    op.drop_table('user_documents')
    with op.batch_alter_table('user_attendance_correction_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_attendance_correction_requests_user_id'))

    op.drop_table('user_attendance_correction_requests')
    with op.batch_alter_table('supporter_feedback_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporter_feedback_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_supporter_feedback_logs_supporter_id'))

    op.drop_table('supporter_feedback_logs')
    with op.batch_alter_table('support_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_threads_user_id'))

    op.drop_table('support_threads')
    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_plans_user_id'))

    op.drop_table('support_plans')
    with op.batch_alter_table('service_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_certificates_municipality_master_id'))

    op.drop_table('service_certificates')
    with op.batch_alter_table('schedule_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_participants_supporter_id'))

    op.drop_table('schedule_participants')
    with op.batch_alter_table('post_transition_follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_transition_follow_ups_user_id'))

    op.drop_table('post_transition_follow_ups')
    with op.batch_alter_table('office_training_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_training_events_training_type'))
        batch_op.drop_index(batch_op.f('ix_office_training_events_office_id'))

    op.drop_table('office_training_events')
    with op.batch_alter_table('office_service_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_service_configurations_office_id'))
        batch_op.drop_index(batch_op.f('ix_office_service_configurations_manager_supporter_id'))

    op.drop_table('office_service_configurations')
    with op.batch_alter_table('monthly_attendance_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_attendance_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_attendance_plans_target_month'))

    op.drop_table('monthly_attendance_plans')
    with op.batch_alter_table('job_retention_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_retention_contracts_user_id'))

    op.drop_table('job_retention_contracts')
    with op.batch_alter_table('job_placement_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_placement_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_placement_logs_employer_id'))

    op.drop_table('job_placement_logs')
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_reporting_staff_id'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_incident_type'))

    op.drop_table('incident_reports')
    with op.batch_alter_table('holistic_support_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holistic_support_policies_user_id'))

    op.drop_table('holistic_support_policies')
    with op.batch_alter_table('document_consent_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_consent_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_consent_logs_document_id'))

    op.drop_table('document_consent_logs')
    with op.batch_alter_table('crisis_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crisis_plans_user_id'))

    op.drop_table('crisis_plans')
    with op.batch_alter_table('compliance_event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_event_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_event_logs_event_type'))

    op.drop_table('compliance_event_logs')
    with op.batch_alter_table('complaint_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_logs_complainant_user_id'))

    op.drop_table('complaint_logs')
    with op.batch_alter_table('committee_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_activity_logs_office_id'))
        batch_op.drop_index(batch_op.f('ix_committee_activity_logs_committee_type_id'))

    op.drop_table('committee_activity_logs')
    with op.batch_alter_table('client_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_invoices_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_invoices_billing_month'))

    op.drop_table('client_invoices')
    with op.batch_alter_table('audit_action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_action_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_action_logs_supporter_id'))

    op.drop_table('audit_action_logs')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_user_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('acquisition_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acquisition_activity_logs_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_acquisition_activity_logs_prospect_user_id'))

    op.drop_table('acquisition_activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status_id'))
        batch_op.drop_index(batch_op.f('ix_users_service_start_date'))
        batch_op.drop_index(batch_op.f('ix_users_primary_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_users_display_name'))

    op.drop_table('users')
    op.drop_table('training_prerequisite_master')
    op.drop_table('supporter_role_link')
    with op.batch_alter_table('supporter_qualifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporter_qualifications_supporter_id'))

    op.drop_table('supporter_qualifications')
    with op.batch_alter_table('supporter_attendance_correction_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporter_attendance_correction_requests_supporter_id'))

    op.drop_table('supporter_attendance_correction_requests')
    with op.batch_alter_table('staff_reflection_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_reflection_logs_supporter_id'))

    op.drop_table('staff_reflection_logs')
    op.drop_table('role_permission_link')
    with op.batch_alter_table('office_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_settings_municipality_id'))
        batch_op.drop_index(batch_op.f('ix_office_settings_corporation_id'))

    op.drop_table('office_settings')
    with op.batch_alter_table('job_development_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_development_logs_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_job_development_logs_employer_id'))

    op.drop_table('job_development_logs')
    with op.batch_alter_table('goal_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_assessments_goal_id'))

    op.drop_table('goal_assessments')
    op.drop_table('vendor_master')
    op.drop_table('system_logs')
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporters_email'))

    op.drop_table('supporters')
    op.drop_table('status_master')
    op.drop_table('staff_activity_master')
    op.drop_table('skill_master')
    op.drop_table('service_type_master')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_start_time'))

    op.drop_table('schedules')
    op.drop_table('role_master')
    op.drop_table('qualification_master')
    op.drop_table('product_master')
    op.drop_table('permission_master')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_organization_type'))
        batch_op.drop_index(batch_op.f('ix_organizations_organization_name'))

    op.drop_table('organizations')
    op.drop_table('municipality_master')
    op.drop_table('job_title_master')
    op.drop_table('gender_legal_master')
    with op.batch_alter_table('employer_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employer_master_company_name'))

    op.drop_table('employer_master')
    op.drop_table('document_type_master')
    op.drop_table('disability_type_master')
    op.drop_table('corporations')
    op.drop_table('committee_type_master')
    op.drop_table('assessor_types')
    # ### end Alembic commands ###
