"""V1_1_Final_Structure_Consolidated

Revision ID: 397e26a3ffa6
Revises: 
Create Date: 2025-11-09 22:13:43.567963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql # JSONBのために必要

# revision identifiers, used by Alembic.
revision = '397e26a3ffa6'
down_revision = None # 後の処理で正しいIDを自動設定
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 新規テーブルの作成 (パーミッション、ログ) ---
    op.create_table('system_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('job_title_permissions',
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title_master.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['system_permissions.id'], ),
    sa.PrimaryKeyConstraint('job_title_id', 'permission_id')
    )
    
    # ★ 修正: SystemAdminActionLog (致命的なエラー修正)
    op.create_table('system_admin_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False), # FKのためデフォルト不要
    sa.Column('action_type', sa.String(length=100), nullable=False, server_default=text("''")), # ★ 修正: 文字列デフォルト
    sa.Column('timestamp', sa.DateTime(), nullable=False, server_default=text('now()')), # ★ 修正: TIMESTAMPのデフォルト
    sa.Column('pin_approval_hash', sa.String(length=128), nullable=False, server_default=text("''")), # ★ 修正: 文字列デフォルト
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # --- 既存テーブルの ALTER (NOT NULL 制約の修正) ---
    
    with op.batch_alter_table('job_title_master', schema=None) as batch_op:
        # ★ 修正: 既存データに False を設定
        batch_op.add_column(sa.Column('is_filing_required', sa.Boolean(), nullable=False, server_default=text('false')))
        batch_op.add_column(sa.Column('is_system_admin', sa.Boolean(), nullable=False, server_default=text('false')))
        
        # job_type にもデフォルトを強制
        batch_op.alter_column('job_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default=text("'LEGAL'"))
        
        batch_op.create_index(batch_op.f('ix_job_title_master_job_type'), ['job_type'], unique=False)
        batch_op.drop_column('is_compliance_role') # 旧カラムを削除

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=128), nullable=True)) # NULLは許容

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.drop_column('pin_hash')

    with op.batch_alter_table('job_title_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_compliance_role', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_job_title_master_job_type'))
        batch_op.drop_column('is_system_admin')
        batch_op.drop_column('is_filing_required')

    op.drop_table('system_admin_action_logs')
    op.drop_table('job_title_permissions')
    op.drop_table('system_permissions')
    # ### end Alembic commands ###
