"""3ロール分離（システム・組織・法令職務）の実装

Revision ID: 39ab862908cc
Revises: 6a176deff222
Create Date: 2025-11-09 15:25:41.380727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ab862908cc'
down_revision = '6a176deff222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_title_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('is_compliance_role', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supporter_job_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title_master.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'office_settings', ['office_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('office_id')

    op.drop_table('supporter_job_assignments')
    op.drop_table('job_title_master')
    # ### end Alembic commands ###
