"""add status to user daily schedules

Revision ID: 402734b2ff7b
Revises: 79343ab4db3f
Create Date: 2026-06-13 11:00:08.622544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402734b2ff7b'
down_revision = '79343ab4db3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_daily_schedules', sa.Column('status', sa.String(length=30), nullable=True))
    op.execute("UPDATE user_daily_schedules SET status = 'CONFIRMED'")
    op.alter_column('user_daily_schedules', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
