"""Added SharedNote and NoteVersion models for collaboration

Revision ID: 4d4fc3e07555
Revises: 073b79276d87
Create Date: 2025-11-23 20:01:45.186269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4fc3e07555'
down_revision = '073b79276d87'
branch_labels = None
depends_on = None


# backend/migrations/versions/4d4fc3e07555_...py 内の upgrade() 関数

def upgrade():
    # ★ 以下の SharedNote および NoteVersion テーブルの作成を追加 ★
    op.create_table('shared_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('office_id', sa.Integer(), sa.ForeignKey('office_settings.id'), nullable=False, index=True),
        sa.Column('note_type', sa.String(length=50), nullable=False),
        sa.Column('linked_entity_type', sa.String(length=50), nullable=True),
        sa.Column('linked_entity_id', sa.Integer(), nullable=True, index=True),
        sa.Column('is_archived', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # op.create_index(op.f('ix_shared_notes_linked_entity_id'), 'shared_notes', ['linked_entity_id'], unique=False)
    # op.create_index(op.f('ix_shared_notes_office_id'), 'shared_notes', ['office_id'], unique=False)
    
    op.create_table('note_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('note_id', sa.Integer(), sa.ForeignKey('shared_notes.id'), nullable=False),
        sa.Column('content_snapshot', sa.Text(), nullable=False),
        sa.Column('supporter_id', sa.Integer(), sa.ForeignKey('supporters.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('note_id', 'version_number', name='uq_note_version_number')
    )
    # op.create_index(op.f('ix_note_versions_note_id'), 'note_versions', ['note_id'], unique=False)


    # ### commands auto generated by Alembic - please adjust! ###
    # ★ NOTE: 既存の drop_constraint は、一旦削除せずにコメントアウトすることを推奨します。
    #          この削除操作が不要であることを確認するために再検討が必要です。
    # with op.batch_alter_table('supporters', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('uq_supporters_staff_code'), type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_supporters_staff_code'), ['staff_code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
