"""Add user_id to monitorings table

Revision ID: 501832410af0
Revises: a782adaad418
Create Date: 2025-11-11 19:47:34.729958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501832410af0'
down_revision = 'a782adaad418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitorings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitorings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
