"""add_approval_workflow_to_service_certificates

Revision ID: 505a317e3f2d
Revises: 8d433c1c1e60
Create Date: 2026-06-13 12:11:15.785422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505a317e3f2d'
down_revision = '8d433c1c1e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False, server_default='ACTIVE'))
        batch_op.add_column(sa.Column('created_by_supporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_supporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_supporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'supporters', ['created_by_supporter_id'], ['id'])
        batch_op.create_foreign_key(None, 'supporters', ['submitted_by_supporter_id'], ['id'])
        batch_op.create_foreign_key(None, 'supporters', ['reviewed_by_supporter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('review_reason')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_supporter_id')
        batch_op.drop_column('submitted_by_supporter_id')
        batch_op.drop_column('created_by_supporter_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
