"""feat: added ISP_Continuity_Gap_Log table and relationships for continuity audit

Revision ID: 58f6f847af97
Revises: 87d1bc094f15
Create Date: 2025-11-29 11:24:17.633856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f6f847af97'
down_revision = '87d1bc094f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isp_continuity_gap_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Previous_Plan_ID', sa.Integer(), nullable=False),
    sa.Column('Gap_Reason_Type', sa.Enum('ABSENCE_HOSPITAL', 'ABSENCE_PRIVATE', 'TERMINATION_VOLUNTARY', 'OTHER', name='gap_reason_type_enum'), nullable=False),
    sa.Column('Gap_Reason_Detail', sa.Text(), nullable=False),
    sa.Column('Gap_Start_Date', sa.Date(), nullable=False),
    sa.Column('Gap_End_Date', sa.Date(), nullable=False),
    sa.Column('Responsible_ID', sa.String(length=50), nullable=False),
    sa.Column('Commit_Timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Previous_Plan_ID'], ['support_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('isp_continuity_gap_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_isp_continuity_gap_logs_Previous_Plan_ID'), ['Previous_Plan_ID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('isp_continuity_gap_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_isp_continuity_gap_logs_Previous_Plan_ID'))

    op.drop_table('isp_continuity_gap_logs')
    # ### end Alembic commands ###
