"""add logical delete columns to case_conference_logs

Revision ID: 5b6ab204be95
Revises: 6a39be1b3098
Create Date: 2026-06-06 14:59:43.421860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b6ab204be95'
down_revision = '6a39be1b3098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unresponsive_risk_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unresponsive_risk_counters_linked_entity_id'))
        batch_op.drop_index(batch_op.f('ix_unresponsive_risk_counters_supporter_id'))

    op.drop_table('unresponsive_risk_counters')

    op.create_table('unresolved_risk_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('cumulative_count', sa.Integer(), nullable=False),
    sa.Column('last_unresolved_at', sa.DateTime(), nullable=False),
    sa.Column('linked_entity_id', sa.Integer(), nullable=True),
    sa.Column('linked_entity_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supporter_id', 'risk_type', name='uq_urac_supporter_risk')
    )
    with op.batch_alter_table('unresolved_risk_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unresolved_risk_counters_linked_entity_id'), ['linked_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unresolved_risk_counters_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('case_conference_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_conference_log_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_conference_log_id'], ['case_conference_logs.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_conference_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_conference_participants_case_conference_log_id'), ['case_conference_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_conference_participants_supporter_id'), ['supporter_id'], unique=False)

    with op.batch_alter_table('audit_action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_supporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('before_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('after_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_audit_action_logs_supporter_id'))
        batch_op.create_index(batch_op.f('ix_audit_action_logs_actor_supporter_id'), ['actor_supporter_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('audit_action_logs_supporter_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'supporters', ['actor_supporter_id'], ['id'])
        batch_op.drop_column('target_table')
        batch_op.drop_column('target_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('action_type')
        batch_op.drop_column('supporter_id')
        batch_op.drop_column('change_details')

    with op.batch_alter_table('case_conference_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'supporters', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('monitoring_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'supporters', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('office_additive_filings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'supporters', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delete_reason', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'supporters', ['deleted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('delete_reason')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('office_additive_filings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('delete_reason')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('monitoring_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('delete_reason')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('case_conference_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('delete_reason')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('audit_action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supporter_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_table', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_action_logs_supporter_id_fkey'), 'supporters', ['supporter_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_audit_action_logs_actor_supporter_id'))
        batch_op.create_index(batch_op.f('ix_audit_action_logs_supporter_id'), ['supporter_id'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('reason')
        batch_op.drop_column('after_value')
        batch_op.drop_column('before_value')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('action')
        batch_op.drop_column('actor_supporter_id')

    op.create_table('unresponsive_risk_counters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supporter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cumulative_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_ignored_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('linked_entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('linked_entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], name=op.f('unresponsive_risk_counters_supporter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('unresponsive_risk_counters_pkey')),
    sa.UniqueConstraint('supporter_id', 'risk_type', name=op.f('uq_urac_supporter_risk'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('unresponsive_risk_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unresponsive_risk_counters_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unresponsive_risk_counters_linked_entity_id'), ['linked_entity_id'], unique=False)

    with op.batch_alter_table('case_conference_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_conference_participants_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_case_conference_participants_case_conference_log_id'))

    op.drop_table('case_conference_participants')
    with op.batch_alter_table('unresolved_risk_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unresolved_risk_counters_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_unresolved_risk_counters_linked_entity_id'))

    op.drop_table('unresolved_risk_counters')
    # ### end Alembic commands ###
