"""Userモデルにdisplay_nameを追加し、last/first_nameを任意に変更

Revision ID: 6a176deff222
Revises: cdaac62506c7
Create Date: 2025-11-08 19:15:25.442529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a176deff222'
down_revision = 'cdaac62506c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
       with op.batch_alter_table('users', schema=None) as batch_op:
       # 1. まずはNULLを許可して列を追加
              batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))

       # 2. ★ 既存データの display_name を first_name で埋める (応急処置) ★
       # (既存の利用者がいる場合、'display_name'がNULLのままNOT NULL制約をかけられないため)
       op.execute("UPDATE users SET display_name = first_name WHERE display_name IS NULL")

       # 3. 応急処置が終わったら、NULLを禁止する
       with op.batch_alter_table('users', schema=None) as batch_op:
              batch_op.alter_column('display_name', existing_type=sa.String(length=100), nullable=False)
              batch_op.alter_column('last_name', existing_type=sa.VARCHAR(length=50), nullable=True)
              batch_op.alter_column('first_name', existing_type=sa.VARCHAR(length=50), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
