"""add_employment_shift_pattern_table

Revision ID: 6a39be1b3098
Revises: 95887ea76a01
Create Date: 2026-05-17 15:32:42.905400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a39be1b3098'
down_revision = '95887ea76a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_shift_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employment_shift_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employment_shift_patterns_supporter_id'), ['supporter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_shift_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_shift_patterns_supporter_id'))

    op.drop_table('employment_shift_patterns')
    # ### end Alembic commands ###
