"""Add TrainingTypeMaster and is_confidential

Revision ID: 70afea224c2a
Revises: db4f2c07a745
Create Date: 2025-11-18 21:32:05.833276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70afea224c2a'
down_revision = 'db4f2c07a745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_type_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('required_frequency_months', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_type_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confidential', sa.Boolean(), nullable=True))

    with op.batch_alter_table('office_training_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_type_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_office_training_events_training_type'))
        batch_op.create_index(batch_op.f('ix_office_training_events_training_type_id'), ['training_type_id'], unique=False)
        batch_op.create_foreign_key(None, 'training_type_master', ['training_type_id'], ['id'])
        batch_op.drop_column('training_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office_training_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_office_training_events_training_type_id'))
        batch_op.create_index(batch_op.f('ix_office_training_events_training_type'), ['training_type'], unique=False)
        batch_op.drop_column('training_type_id')

    with op.batch_alter_table('document_type_master', schema=None) as batch_op:
        batch_op.drop_column('is_confidential')

    op.drop_table('training_type_master')
    # ### end Alembic commands ###
