"""add schedule location type and max service days

Revision ID: 79343ab4db3f
Revises: merge_218388db7269_3c8f9a1b2c34
Create Date: 2026-06-13 10:57:44.918030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79343ab4db3f'
down_revision = 'merge_218388db7269_3c8f9a1b2c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('granted_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_service_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user_schedule_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schedule_templates', schema=None) as batch_op:
        batch_op.drop_column('location_type')

    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.drop_column('location_type')

    with op.batch_alter_table('granted_services', schema=None) as batch_op:
        batch_op.drop_column('max_service_days')

    # ### end Alembic commands ###
