"""add schedule_kind

Revision ID: 795ad91856a4
Revises: e50ced1ad463
Create Date: 2026-06-14 08:13:14.699299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795ad91856a4'
down_revision = 'e50ced1ad463'
branch_labels = None
"""add schedule_kind

Revision ID: 795ad91856a4
Revises: e50ced1ad463
Create Date: 2026-06-14 08:13:14.699299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795ad91856a4'
down_revision = 'e50ced1ad463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_kind', sa.String(length=30), server_default='NORMAL', nullable=False))
        batch_op.drop_column('schedule_status')
        batch_op.drop_column('is_scheduled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_scheduled', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('schedule_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('schedule_kind')

    # ### end Alembic commands ###
