"""FEAT(models): Added V10.2 models for URAC, SessionLock, SharedNote, and Staff Wellness

Revision ID: 87d1bc094f15
Revises: 4d4fc3e07555
Create Date: 2025-11-28 19:20:27.351850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d1bc094f15'
down_revision = '4d4fc3e07555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_transfer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('transfer_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('transfer_reason_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approver_supporter_id', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_transfer_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_transfer_logs_corporation_id'), ['corporation_id'], unique=False)

    op.create_table('staff_wellness_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('rating_score', sa.Integer(), nullable=True),
    sa.Column('narrative_notes', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_wellness_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_wellness_logs_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('unresponsive_risk_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('cumulative_count', sa.Integer(), nullable=False),
    sa.Column('last_ignored_at', sa.DateTime(), nullable=False),
    sa.Column('linked_entity_id', sa.Integer(), nullable=True),
    sa.Column('linked_entity_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supporter_id', 'risk_type', name='uq_urac_supporter_risk')
    )
    with op.batch_alter_table('unresponsive_risk_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unresponsive_risk_counters_linked_entity_id'), ['linked_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unresponsive_risk_counters_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('session_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_pii_session', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('session_start_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_locks_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_locks_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_versions_note_id'), ['note_id'], unique=False)

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_supporters_staff_code'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_supporters_staff_code'), ['staff_code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_versions_note_id'))

    with op.batch_alter_table('session_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_locks_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_locks_supporter_id'))

    op.drop_table('session_locks')
    with op.batch_alter_table('unresponsive_risk_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unresponsive_risk_counters_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_unresponsive_risk_counters_linked_entity_id'))

    op.drop_table('unresponsive_risk_counters')
    with op.batch_alter_table('staff_wellness_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_wellness_logs_supporter_id'))

    op.drop_table('staff_wellness_logs')
    with op.batch_alter_table('corporate_transfer_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_transfer_logs_corporation_id'))

    op.drop_table('corporate_transfer_logs')
    # ### end Alembic commands ###
