"""V1.1_ServiceRecord_Unified_and_Chat_Refactor

Revision ID: 89d74be142a6
Revises: 2a725badd20a
Create Date: 2025-11-08 09:44:23.534562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89d74be142a6'
down_revision = '2a725badd20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 1. 新しいテーブルの作成 (チャット機能) ---
    op.create_table('chat_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    # ★ 修正: server_default を追加
    sa.Column('channel_type', sa.String(length=50), nullable=False, server_default=sa.text("'STAFF_ONLY'")),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    # ★ 修正: server_default を追加
    sa.Column('status', sa.String(length=50), nullable=False, server_default=sa.text("'open'")),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')), # ★ 修正
    # ★ 修正: server_default を追加
    sa.Column('thread_type', sa.String(length=50), nullable=False, server_default=sa.text("'PERSONAL'")),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(supporter_id IS NOT NULL AND user_id IS NULL) OR (supporter_id IS NULL AND user_id IS NOT NULL)', name='ck_channel_participant_user_type'),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    # ★ 修正: server_default を追加
    sa.Column('status', sa.String(length=50), nullable=False, server_default=sa.text("'pending'")),
    sa.Column('approver_supporter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')), # ★ 修正
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_channel_id', sa.Integer(), nullable=True),
    sa.Column('target_schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approver_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['created_channel_id'], ['chat_channels.id'], ),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('sender_supporter_id', sa.Integer(), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False, server_default=sa.text('now()')), # ★ 修正
    sa.CheckConstraint('(sender_supporter_id IS NOT NULL AND sender_user_id IS NULL) OR (sender_supporter_id IS NULL AND sender_user_id IS NOT NULL)', name='ck_channel_message_sender'),
    sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ),
    sa.ForeignKeyConstraint(['sender_supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_requests_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_requests_status'), ['status'], unique=False)

    
    # --- 2. 既存テーブルの「列」追加 (NotNull違反を修正) ---

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_consent_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attending_supporter_id', sa.Integer(), nullable=True))
        # ★ 修正: server_default を追加
        batch_op.add_column(sa.Column('is_finalized', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_foreign_key('fk_attendance_records_attending_supporter', 'supporters', ['attending_supporter_id'], ['id']) # ★ 修正: FKに名前を付ける

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        # ★ 修正: 既存データがあるため、最初は NULLを許可 (nullable=True)
        batch_op.add_column(sa.Column('thread_id', sa.Integer(), nullable=True)) 
        batch_op.add_column(sa.Column('sender_supporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sender_user_id', sa.Integer(), nullable=True))
        # ★ 修正: server_default を追加
        batch_op.add_column(sa.Column('is_internal_note', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        
        batch_op.drop_constraint('chat_messages_target_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chat_messages_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chat_messages_recipient_id_fkey', type_='foreignkey')
        
        batch_op.create_foreign_key('fk_chat_messages_sender_supporter', 'supporters', ['sender_supporter_id'], ['id']) # ★ 修正: FKに名前を付ける
        batch_op.create_foreign_key('fk_chat_messages_sender_user', 'users', ['sender_user_id'], ['id']) # ★ 修正: FKに名前を付ける
        batch_op.create_foreign_key('fk_chat_messages_thread', 'support_threads', ['thread_id'], ['id']) # ★ 修正: FKに名前を付ける
        
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('target_user_id')
        batch_op.drop_column('is_sensitive')
        batch_op.drop_column('is_read')
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('corporations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corporation_seal_image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('office_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office_seal_image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('pre_enrollment_logs', schema=None) as batch_op:
        # ★ 修正: 既存データがあるため、最初は NULLを許可 (nullable=True)
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True)) 
        batch_op.drop_constraint('pre_enrollment_logs_prospect_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_pre_enrollment_logs_user', 'users', ['user_id'], ['id']) # ★ 修正: FKに名前を付ける
        batch_op.drop_column('prospect_id')

    with op.batch_alter_table('record_supporters', schema=None) as batch_op:
        # ★ 修正: 既存データ(NULL)があるため、NULLを許可 (nullable=True)
        # (この後、データ移行バッチで external_record_id -> service_record_id へデータを移す)
        batch_op.alter_column('service_record_id',
                              existing_type=sa.INTEGER(),
                              nullable=True) 
        batch_op.drop_constraint('record_supporters_external_record_id_fkey', type_='foreignkey')
        batch_op.drop_column('external_record_id')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_schedules_service_location', 'service_location_master', ['service_location_id'], ['id']) # ★ 修正: FKに名前を付ける

    with op.batch_alter_table('service_location_master', schema=None) as batch_op:
        # ★ 修正: server_default を追加
        batch_op.add_column(sa.Column('is_offsite_work_location', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('contract_document_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('contract_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_end_date', sa.Date(), nullable=True))
        # ★ 修正: server_default を追加
        batch_op.alter_column('is_offsite',
                              existing_type=sa.BOOLEAN(),
                              nullable=False,
                              server_default=sa.text('false'))

    with op.batch_alter_table('service_record_additives', schema=None) as batch_op:
        # ★ 修正: 既存データ(NULL)があるため、NULLを許可 (nullable=True)
        batch_op.alter_column('service_record_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.drop_constraint('service_record_additives_external_record_id_fkey', type_='foreignkey')
        batch_op.drop_column('external_record_id')

    with op.batch_alter_table('service_records', schema=None) as batch_op:
        # ★ 修正: 既存データがあるため、最初は NULLを許可 (nullable=True)
        batch_op.add_column(sa.Column('service_location_id', sa.Integer(), nullable=True)) 
        batch_op.add_column(sa.Column('user_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_service_records_service_location', 'service_location_master', ['service_location_id'], ['id']) # ★ 修正: FKに名前を付ける

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seal_image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seal_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('line_id', sa.String(length=255), nullable=True))
        # ★ 修正: server_default を追加 (既存のNULLを 1='利用中' と仮定)
        batch_op.alter_column('status_id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              server_default=sa.text('1'))
        batch_op.create_index(batch_op.f('ix_users_line_id'), ['line_id'], unique=True)

    
    # --- 3. 古いテーブルの削除 (★ 依存関係の順序を修正 ★) ---
    
    # 子テーブル (prospectsを参照) を先に削除
    # (pre_enrollment_logs は prospect_id を削除したのでOK)
    
    # 子テーブル (external_support_recordsを参照) のFK削除は上記で実施済み
    
    # ★ 修正: 親テーブルを「最後」に削除する
    op.drop_table('prospects')
    op.drop_table('external_support_records')
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_line_id'))
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('line_id')
        batch_op.drop_column('seal_image_url')

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.drop_column('seal_image_url')

    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_confirmed_at')
        batch_op.drop_column('service_location_id')

    with op.batch_alter_table('service_record_additives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_record_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('service_record_additives_external_record_id_fkey'), 'external_support_records', ['external_record_id'], ['id'])
        batch_op.alter_column('service_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('service_location_master', schema=None) as batch_op:
        batch_op.alter_column('is_offsite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('contract_end_date')
        batch_op.drop_column('contract_start_date')
        batch_op.drop_column('contract_document_url')
        batch_op.drop_column('is_offsite_work_location')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_location_id')

    with op.batch_alter_table('record_supporters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_record_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('record_supporters_external_record_id_fkey'), 'external_support_records', ['external_record_id'], ['id'])
        batch_op.alter_column('service_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pre_enrollment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prospect_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pre_enrollment_logs_prospect_id_fkey'), 'prospects', ['prospect_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('office_settings', schema=None) as batch_op:
        batch_op.drop_column('office_seal_image_url')

    with op.batch_alter_table('corporations', schema=None) as batch_op:
        batch_op.drop_column('corporation_seal_image_url')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_sensitive', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_messages_recipient_id_fkey'), 'supporters', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('chat_messages_sender_id_fkey'), 'supporters', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('chat_messages_target_user_id_fkey'), 'users', ['target_user_id'], ['id'])
        batch_op.drop_column('is_internal_note')
        batch_op.drop_column('sender_user_id')
        batch_op.drop_column('sender_supporter_id')
        batch_op.drop_column('thread_id')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_finalized')
        batch_op.drop_column('attending_supporter_id')
        batch_op.drop_column('user_consent_date')

    op.create_table('external_support_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('actual_work_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('support_location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('support_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_billable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('external_support_records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('external_support_records_pkey'))
    )
    op.create_table('prospects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name_kana', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('first_name_kana', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referral_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referral_source_id'], ['referral_source_master.id'], name=op.f('prospects_referral_source_id_fkey')),
    sa.ForeignKeyConstraint(['status_id'], ['status_master.id'], name=op.f('prospects_status_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prospects_pkey'))
    )
    with op.batch_alter_table('user_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_requests_status'))
        batch_op.drop_index(batch_op.f('ix_user_requests_request_type'))

    op.drop_table('user_requests')
    op.drop_table('support_threads')
    op.drop_table('channel_participants')
    op.drop_table('channel_messages')
    op.drop_table('chat_channels')
    # ### end Alembic commands ###
