"""fix: added missing user billings relation

Revision ID: 89e06588033e
Revises: 04b649b976fc
Create Date: 2025-11-29 15:29:51.817319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e06588033e'
down_revision = '04b649b976fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('daily_log_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_audit_passed', sa.Boolean(), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['support_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_data_daily_log_id'), ['daily_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_data_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_data_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('government_fee_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_daily_logs', sa.Boolean(), nullable=True))
        batch_op.drop_column('needs_daily_record')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_fee_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_daily_record', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('needs_daily_logs')

    with op.batch_alter_table('billing_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_billing_data_plan_id'))
        batch_op.drop_index(batch_op.f('ix_billing_data_daily_log_id'))

    op.drop_table('billing_data')
    # ### end Alembic commands ###
