"""add recipient_number and contract details to certificate related tables

Revision ID: 8d433c1c1e60
Revises: 3676eb9031ab
Create Date: 2026-06-13 11:32:01.213802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d433c1c1e60'
down_revision = '3676eb9031ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_report_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_end_used_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('copayment_limits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_management_required', sa.Boolean(), nullable=False))

    with op.batch_alter_table('granted_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_service_days_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('granted_amount_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('granted_amount_end_date', sa.Date(), nullable=True))

    with op.batch_alter_table('service_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_number', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_certificates', schema=None) as batch_op:
        batch_op.drop_column('recipient_number')

    with op.batch_alter_table('granted_services', schema=None) as batch_op:
        batch_op.drop_column('granted_amount_end_date')
        batch_op.drop_column('granted_amount_start_date')
        batch_op.drop_column('max_service_days_type')

    with op.batch_alter_table('copayment_limits', schema=None) as batch_op:
        batch_op.drop_column('is_management_required')

    with op.batch_alter_table('contract_report_details', schema=None) as batch_op:
        batch_op.drop_column('contract_end_used_days')
        batch_op.drop_column('contract_end_date')

    # ### end Alembic commands ###
