"""add unique constraint to user_daily_log

Revision ID: 90866e1d52b9
Revises: d11558d2f9de
Create Date: 2026-07-18 13:57:22.259601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90866e1d52b9'
down_revision = 'd11558d2f9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_logs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_daily_log_user_date', ['user_id', 'log_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_logs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_daily_log_user_date', type_='unique')

    # ### end Alembic commands ###
