"""Add tenant and SSO integration settings

Revision ID: 95887ea76a01
Revises: 89e06588033e
Create Date: 2026-05-16 06:03:12.851630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95887ea76a01'
down_revision = '89e06588033e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('integration_settings', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_corporations_tenant_id'), ['tenant_id'], unique=True)

    with op.batch_alter_table('supporter_pii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sso_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sso_account_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_supporter_pii_sso_account_id'), ['sso_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supporter_pii_sso_provider'), ['sso_provider'], unique=False)
        batch_op.create_unique_constraint('uq_supporterpii_sso', ['sso_provider', 'sso_account_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporter_pii', schema=None) as batch_op:
        batch_op.drop_constraint('uq_supporterpii_sso', type_='unique')
        batch_op.drop_index(batch_op.f('ix_supporter_pii_sso_provider'))
        batch_op.drop_index(batch_op.f('ix_supporter_pii_sso_account_id'))
        batch_op.drop_column('sso_account_id')
        batch_op.drop_column('sso_provider')

    with op.batch_alter_table('corporations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporations_tenant_id'))
        batch_op.drop_column('integration_settings')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
