"""refactor_daily_logs_and_support_records

Revision ID: a69a16b6b100
Revises: 5b6ab204be95
Create Date: 2026-06-08 12:36:41.415086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a69a16b6b100'
down_revision = '5b6ab204be95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_log_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_id')
    )
    op.create_table('supporter_form_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('draft_key', sa.String(length=100), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supporter_id', 'draft_key', name='uq_supporter_form_draft')
    )
    with op.batch_alter_table('supporter_form_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supporter_form_drafts_draft_key'), ['draft_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_supporter_form_drafts_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('user_daily_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('external_location_detail', sa.Text(), nullable=True),
    sa.Column('log_status', sa.String(length=30), nullable=False),
    sa.Column('sleep_quality_score', sa.Integer(), nullable=True),
    sa.Column('physical_condition_score', sa.Integer(), nullable=True),
    sa.Column('grooming_check', sa.Boolean(), nullable=True),
    sa.Column('user_self_evaluation', sa.Text(), nullable=True),
    sa.Column('staff_effectiveness_flag', sa.Boolean(), nullable=True),
    sa.Column('user_effectiveness_flag', sa.Boolean(), nullable=True),
    sa.Column('support_content_notes', sa.Text(), nullable=False),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('morning_completed', sa.Boolean(), nullable=True),
    sa.Column('evening_completed', sa.Boolean(), nullable=True),
    sa.Column('failure_factor_id', sa.Integer(), nullable=True),
    sa.Column('challenge_analysis_notes', sa.Text(), nullable=True),
    sa.Column('heartwarming_episode', sa.Text(), nullable=True),
    sa.Column('auto_created', sa.Boolean(), nullable=True),
    sa.Column('created_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['failure_factor_id'], ['failure_factor_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_logs_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_daily_logs_user_id'), ['user_id'], unique=False)

    op.create_table('support_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('support_start_time', sa.DateTime(), nullable=True),
    sa.Column('support_end_time', sa.DateTime(), nullable=True),
    sa.Column('support_record_type', sa.String(length=30), nullable=False),
    sa.Column('support_plan_id', sa.Integer(), nullable=True),
    sa.Column('support_goal_id', sa.Integer(), nullable=True),
    sa.Column('support_content', sa.Text(), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('observation_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['support_goal_id'], ['individual_support_goals.id'], ),
    sa.ForeignKeyConstraint(['support_plan_id'], ['support_plans.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_records_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_records_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('absence_response_logs', schema=None) as batch_op:
        batch_op.drop_constraint('absence_response_logs_daily_log_id_key', type_='unique')
        batch_op.drop_constraint('absence_response_logs_daily_log_id_fkey', type_='foreignkey')

    with op.batch_alter_table('billing_data', schema=None) as batch_op:
        batch_op.drop_index('ix_billing_data_daily_log_id')
        batch_op.drop_constraint('billing_data_daily_log_id_fkey', type_='foreignkey')

    with op.batch_alter_table('break_records', schema=None) as batch_op:
        batch_op.drop_index('ix_break_records_daily_log_id')
        batch_op.drop_constraint('break_records_daily_log_id_fkey', type_='foreignkey')

    with op.batch_alter_table('daily_productivity_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_productivity_logs_daily_log_id')
        batch_op.drop_constraint('daily_productivity_logs_daily_log_id_fkey', type_='foreignkey')

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_log_date'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_user_id'))

    op.drop_table('daily_log_activities')
    op.drop_table('daily_logs')

    with op.batch_alter_table('absence_response_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_daily_log_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['user_daily_log_id'])
        batch_op.create_foreign_key(None, 'user_daily_logs', ['user_daily_log_id'], ['id'])
        batch_op.drop_column('daily_log_id')

    with op.batch_alter_table('billing_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_daily_log_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_billing_data_user_daily_log_id'), ['user_daily_log_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_daily_logs', ['user_daily_log_id'], ['id'])
        batch_op.drop_column('daily_log_id')

    with op.batch_alter_table('break_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_daily_log_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_break_records_user_daily_log_id'), ['user_daily_log_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_daily_logs', ['user_daily_log_id'], ['id'])
        batch_op.drop_column('daily_log_id')

    with op.batch_alter_table('case_conference_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_participated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('reason_for_user_absence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_sabikan_digital_declaration', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('absence_monitoring_summary', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_case_conference_logs_support_plan_id'), ['support_plan_id'], unique=False)
        batch_op.create_foreign_key(None, 'support_plans', ['support_plan_id'], ['id'])

    with op.batch_alter_table('daily_productivity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_daily_log_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_daily_productivity_logs_user_daily_log_id'), ['user_daily_log_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_daily_logs', ['user_daily_log_id'], ['id'])
        batch_op.drop_column('daily_log_id')

    with op.batch_alter_table('long_term_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenges', sa.Text(), nullable=True))

    with op.batch_alter_table('office_service_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('regional_category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('target_disabilities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cooperating_medical_institution', sa.Text(), nullable=True))

    with op.batch_alter_table('office_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fax_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_address', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('representative_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('role_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    with op.batch_alter_table('staff_activity_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_direct_support', sa.Boolean(), nullable=True))

    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_created_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('explained_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('consented_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('activated_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('timeline_deviation_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('supporter_timecards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('check_out_location', sa.String(length=255), nullable=True))

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_overlap_calculation', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_user_code'), ['user_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_code'))
        batch_op.drop_column('user_code')

    with op.batch_alter_table('supporters', schema=None) as batch_op:
        batch_op.drop_column('allow_overlap_calculation')

    with op.batch_alter_table('supporter_timecards', schema=None) as batch_op:
        batch_op.drop_column('check_out_location')
        batch_op.drop_column('check_in_location')

    with op.batch_alter_table('support_plans', schema=None) as batch_op:
        batch_op.drop_column('timeline_deviation_reason')
        batch_op.drop_column('activated_at')
        batch_op.drop_column('consented_at')
        batch_op.drop_column('explained_at')
        batch_op.drop_column('draft_created_at')

    with op.batch_alter_table('staff_activity_master', schema=None) as batch_op:
        batch_op.drop_column('is_direct_support')

    with op.batch_alter_table('role_master', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('office_settings', schema=None) as batch_op:
        batch_op.drop_column('representative_name')
        batch_op.drop_column('email_address')
        batch_op.drop_column('fax_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')
        batch_op.drop_column('postal_code')

    with op.batch_alter_table('office_service_configurations', schema=None) as batch_op:
        batch_op.drop_column('cooperating_medical_institution')
        batch_op.drop_column('target_disabilities')
        batch_op.drop_column('regional_category')
        batch_op.drop_column('designation_expiry_date')

    with op.batch_alter_table('long_term_goals', schema=None) as batch_op:
        batch_op.drop_column('challenges')

    with op.batch_alter_table('daily_productivity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_log_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('daily_productivity_logs_daily_log_id_fkey'), 'daily_logs', ['daily_log_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_daily_productivity_logs_user_daily_log_id'))
        batch_op.create_index(batch_op.f('ix_daily_productivity_logs_daily_log_id'), ['daily_log_id'], unique=False)
        batch_op.drop_column('user_daily_log_id')

    with op.batch_alter_table('case_conference_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_case_conference_logs_support_plan_id'))
        batch_op.drop_column('absence_monitoring_summary')
        batch_op.drop_column('is_sabikan_digital_declaration')
        batch_op.drop_column('reason_for_user_absence')
        batch_op.drop_column('user_participated')
        batch_op.drop_column('support_plan_id')

    with op.batch_alter_table('break_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_log_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('break_records_daily_log_id_fkey'), 'daily_logs', ['daily_log_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_break_records_user_daily_log_id'))
        batch_op.create_index(batch_op.f('ix_break_records_daily_log_id'), ['daily_log_id'], unique=False)
        batch_op.drop_column('user_daily_log_id')

    with op.batch_alter_table('billing_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_log_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('billing_data_daily_log_id_fkey'), 'daily_logs', ['daily_log_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_billing_data_user_daily_log_id'))
        batch_op.create_index(batch_op.f('ix_billing_data_daily_log_id'), ['daily_log_id'], unique=False)
        batch_op.drop_column('user_daily_log_id')

    with op.batch_alter_table('absence_response_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_log_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('absence_response_logs_daily_log_id_fkey'), 'daily_logs', ['daily_log_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('absence_response_logs_daily_log_id_key'), ['daily_log_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('user_daily_log_id')

    op.create_table('daily_log_activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('daily_log_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('support_goal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supporter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('support_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('support_end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('work_preparation_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('support_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], name=op.f('daily_log_activities_daily_log_id_fkey')),
    sa.ForeignKeyConstraint(['support_goal_id'], ['individual_support_goals.id'], name=op.f('daily_log_activities_support_goal_id_fkey')),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], name=op.f('daily_log_activities_supporter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_log_activities_pkey'))
    )
    op.create_table('daily_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sleep_quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('physical_condition_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grooming_check', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_self_evaluation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('staff_effectiveness_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_effectiveness_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('support_content_notes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('heartwarming_episode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('failure_factor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('challenge_analysis_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('log_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('location_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('external_location_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['failure_factor_id'], ['failure_factor_master.id'], name=op.f('daily_logs_failure_factor_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_logs_pkey'))
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_log_date'), ['log_date'], unique=False)

    with op.batch_alter_table('support_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_records_log_date'))

    op.drop_table('support_records')
    with op.batch_alter_table('user_daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_daily_logs_log_date'))

    op.drop_table('user_daily_logs')
    with op.batch_alter_table('supporter_form_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supporter_form_drafts_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_supporter_form_drafts_draft_key'))

    op.drop_table('supporter_form_drafts')
    op.drop_table('user_daily_log_settings')
    # ### end Alembic commands ###
