"""Final_V1_2_Permission_Consolidation

Revision ID: a782adaad418
Revises: 397e26a3ffa6
Create Date: 2025-11-10 20:16:15.773052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a782adaad418'
down_revision = '397e26a3ffa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_filing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title_master.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supporter_job_assignments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_supporter_job_start', ['supporter_id', 'job_title_id', 'start_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporter_job_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_supporter_job_start', type_='unique')

    op.drop_table('job_filing_records')
    # ### end Alembic commands ###
