"""Add user profile models

Revision ID: a80c3fe9678f
Revises: 1567bd64bf05
Create Date: 2025-10-30 08:36:03.333548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80c3fe9678f'
down_revision = '1567bd64bf05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disability_type_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gender_legal_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('municipality_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('municipality_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipality_master_municipality_code'), ['municipality_code'], unique=True)

    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type_id', sa.Integer(), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('billing_municipality_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('copayment_limit', sa.Integer(), nullable=True),
    sa.Column('copayment_start_date', sa.Date(), nullable=True),
    sa.Column('copayment_end_date', sa.Date(), nullable=True),
    sa.Column('service_amount', sa.String(length=50), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('ramp_service_field_index', sa.Integer(), nullable=True),
    sa.Column('ramp_service_amount', sa.String(length=50), nullable=True),
    sa.Column('ramp_contract_date', sa.Date(), nullable=True),
    sa.Column('ramp_contract_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['billing_municipality_id'], ['municipality_master.id'], ),
    sa.ForeignKeyConstraint(['certificate_type_id'], ['certificate_type_master.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_user_id'), ['user_id'], unique=False)

    op.create_table('developmental_history_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_period', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('developmental_history_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developmental_history_items_event_period'), ['event_period'], unique=False)
        batch_op.create_index(batch_op.f('ix_developmental_history_items_user_id'), ['user_id'], unique=False)

    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_contacts_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_contacts_user_id'), ['user_id'], unique=False)

    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('is_living_together', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('health_status', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_members_user_id'), ['user_id'], unique=False)

    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qualification_name', sa.String(length=150), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('issuing_organization', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualifications_user_id'), ['user_id'], unique=False)

    op.create_table('developmental_history_categories_association',
    sa.Column('history_item_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['history_category_master.id'], ),
    sa.ForeignKeyConstraint(['history_item_id'], ['developmental_history_items.id'], ),
    sa.PrimaryKeyConstraint('history_item_id', 'category_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_legal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender_identity', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disability_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disability_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('support_needs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_first_name_kana'), ['first_name_kana'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name_kana'), ['last_name_kana'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_primary_supporter_id'), ['primary_supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status_id'), ['status_id'], unique=False)
        batch_op.create_foreign_key(None, 'disability_type_master', ['disability_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'gender_legal_master', ['gender_legal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_status_id'))
        batch_op.drop_index(batch_op.f('ix_users_start_date'))
        batch_op.drop_index(batch_op.f('ix_users_primary_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_users_last_name_kana'))
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name_kana'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('support_needs')
        batch_op.drop_column('disability_details')
        batch_op.drop_column('disability_type_id')
        batch_op.drop_column('gender_identity')
        batch_op.drop_column('gender_legal_id')

    op.drop_table('developmental_history_categories_association')
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualifications_user_id'))

    op.drop_table('qualifications')
    with op.batch_alter_table('family_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_members_user_id'))

    op.drop_table('family_members')
    with op.batch_alter_table('emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_user_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_contacts_priority'))

    op.drop_table('emergency_contacts')
    with op.batch_alter_table('developmental_history_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developmental_history_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_developmental_history_items_event_period'))

    op.drop_table('developmental_history_items')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_expiry_date'))

    op.drop_table('certificates')
    with op.batch_alter_table('municipality_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipality_master_municipality_code'))

    op.drop_table('municipality_master')
    op.drop_table('gender_legal_master')
    op.drop_table('disability_type_master')
    # ### end Alembic commands ###
