"""Add StaffActivityAllocationLog

Revision ID: ca5e5ee55e38
Revises: 70afea224c2a
Create Date: 2025-11-18 22:16:02.853449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5e5ee55e38'
down_revision = '70afea224c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_activity_allocation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('staff_activity_master_id', sa.Integer(), nullable=False),
    sa.Column('allocated_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_activity_master_id'], ['staff_activity_master.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_activity_allocation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_activity_allocation_logs_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('job_filing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('job_title_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_title_master.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_filing_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_filing_records_office_id'), ['office_id'], unique=False)

    op.create_table('office_additive_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_service_configuration_id', sa.Integer(), nullable=False),
    sa.Column('additive_name', sa.String(length=100), nullable=False),
    sa.Column('is_filed', sa.Boolean(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['office_service_configuration_id'], ['office_service_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('office_additive_filings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_office_additive_filings_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office_additive_filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_office_additive_filings_office_service_configuration_id'))

    op.drop_table('office_additive_filings')
    with op.batch_alter_table('job_filing_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_filing_records_office_id'))

    op.drop_table('job_filing_records')
    with op.batch_alter_table('staff_activity_allocation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_activity_allocation_logs_supporter_id'))

    op.drop_table('staff_activity_allocation_logs')
    # ### end Alembic commands ###
