"""SNS IDを汎用カラムsns_providerに統一

Revision ID: cdaac62506c7
Revises: de7d64d21149
Create Date: 2025-11-08 19:02:43.147998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdaac62506c7'
down_revision = 'de7d64d21149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sns_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sns_account_id', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_line_id'))
        batch_op.drop_index(batch_op.f('ix_users_meta_id'))
        batch_op.drop_index(batch_op.f('ix_users_x_id'))
        batch_op.create_index(batch_op.f('ix_users_sns_account_id'), ['sns_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_sns_provider'), ['sns_provider'], unique=False)
        batch_op.create_unique_constraint('uq_user_sns_auth', ['sns_provider', 'sns_account_id'])
        batch_op.drop_column('x_id')
        batch_op.drop_column('meta_id')
        batch_op.drop_column('line_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meta_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('x_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_user_sns_auth', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_sns_provider'))
        batch_op.drop_index(batch_op.f('ix_users_sns_account_id'))
        batch_op.create_index(batch_op.f('ix_users_x_id'), ['x_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_meta_id'), ['meta_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_line_id'), ['line_id'], unique=True)
        batch_op.drop_column('sns_account_id')
        batch_op.drop_column('sns_provider')

    # ### end Alembic commands ###
