"""add user_daily_log_id to support_record

Revision ID: d11558d2f9de
Revises: eec9fe393f94
Create Date: 2026-07-18 13:48:33.765311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11558d2f9de'
down_revision = 'eec9fe393f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_daily_log_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_support_records_user_daily_log_id'), ['user_daily_log_id'], unique=False)
        batch_op.create_foreign_key(None, 'user_daily_logs', ['user_daily_log_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_support_records_user_daily_log_id'))
        batch_op.drop_column('user_daily_log_id')

    # ### end Alembic commands ###
