"""V2.0 - Finalized logical model structure

Revision ID: db4f2c07a745
Revises: 2c5f03c019a9
Create Date: 2025-11-18 20:39:34.630120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4f2c07a745'
down_revision = '2c5f03c019a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_conference_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_for_user_absence', sa.Text(), nullable=True))

    with op.batch_alter_table('user_pii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_data_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('encrypted_last_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('encrypted_first_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('encrypted_last_name_kana', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('encrypted_first_name_kana', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('encrypted_address', sa.String(length=512), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_pii_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_pii_first_name_kana'))
        batch_op.drop_index(batch_op.f('ix_user_pii_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_pii_last_name_kana'))
        batch_op.create_index(batch_op.f('ix_user_pii_phone_number'), ['phone_number'], unique=False)
        batch_op.drop_column('first_name')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('first_name_kana')
        batch_op.drop_column('last_name')
        batch_op.drop_column('address')
        batch_op.drop_column('last_name_kana')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name_kana', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name_kana', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_pii_phone_number'))
        batch_op.create_index(batch_op.f('ix_user_pii_last_name_kana'), ['last_name_kana'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pii_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pii_first_name_kana'), ['first_name_kana'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pii_first_name'), ['first_name'], unique=False)
        batch_op.drop_column('encrypted_address')
        batch_op.drop_column('encrypted_first_name_kana')
        batch_op.drop_column('encrypted_last_name_kana')
        batch_op.drop_column('encrypted_first_name')
        batch_op.drop_column('encrypted_last_name')
        batch_op.drop_column('encrypted_data_key')

    with op.batch_alter_table('support_conference_logs', schema=None) as batch_op:
        batch_op.drop_column('reason_for_user_absence')

    # ### end Alembic commands ###
