"""SystemLogモデルにdetails列を追加

Revision ID: dc93bc1c965a
Revises: 39ab862908cc
Create Date: 2025-11-09 18:21:05.940185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc93bc1c965a'
down_revision = '39ab862908cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
