"""Userモデルにx_idとmeta_idを追加

Revision ID: de7d64d21149
Revises: 89d74be142a6
Create Date: 2025-11-08 17:48:59.482412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7d64d21149'
down_revision = '89d74be142a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pre_enrollment_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('record_supporters', schema=None) as batch_op:
        batch_op.alter_column('service_record_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('service_record_additives', schema=None) as batch_op:
        batch_op.alter_column('service_record_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.alter_column('service_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_medium', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_meta_id'), ['meta_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_utm_source'), ['utm_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_x_id'), ['x_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_x_id'))
        batch_op.drop_index(batch_op.f('ix_users_utm_source'))
        batch_op.drop_index(batch_op.f('ix_users_meta_id'))
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('meta_id')
        batch_op.drop_column('x_id')

    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.alter_column('service_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('service_record_additives', schema=None) as batch_op:
        batch_op.alter_column('service_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('record_supporters', schema=None) as batch_op:
        batch_op.alter_column('service_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pre_enrollment_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('thread_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
