"""add decision_reason to user_daily_schedules

Revision ID: e50ced1ad463
Revises: 06bfd980e0c2
Create Date: 2026-06-13 22:03:55.688756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50ced1ad463'
down_revision = '06bfd980e0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_daily_schedules', schema=None) as batch_op:
        batch_op.drop_column('decision_reason')

    # ### end Alembic commands ###
