"""add location to support_record

Revision ID: eec9fe393f94
Revises: fa3177e5e8fb
Create Date: 2026-07-18 13:04:38.154161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec9fe393f94'
down_revision = 'fa3177e5e8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location_detail', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_records', schema=None) as batch_op:
        batch_op.drop_column('location_detail')
        batch_op.drop_column('location_type')

    # ### end Alembic commands ###
