"""Add StaffDailyShift, StaffActionLog, StaffDailyReport

Revision ID: fa3177e5e8fb
Revises: 795ad91856a4
Create Date: 2026-07-11 12:40:25.265093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3177e5e8fb'
down_revision = '795ad91856a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('action_timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_content', sa.Text(), nullable=False),
    sa.Column('is_processed_by_ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_action_logs_supporter_id'), ['supporter_id'], unique=False)

    op.create_table('staff_daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.Column('is_ai_draft', sa.Boolean(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_daily_reports_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_daily_reports_target_date'), ['target_date'], unique=False)

    op.create_table('staff_daily_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supporter_id', sa.Integer(), nullable=False),
    sa.Column('office_service_configuration_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('planned_start_time', sa.DateTime(), nullable=False),
    sa.Column('planned_end_time', sa.DateTime(), nullable=False),
    sa.Column('planned_break_minutes', sa.Integer(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['office_service_configuration_id'], ['office_service_configurations.id'], ),
    sa.ForeignKeyConstraint(['supporter_id'], ['supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_daily_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_daily_shifts_office_service_configuration_id'), ['office_service_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_daily_shifts_supporter_id'), ['supporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_daily_shifts_target_date'), ['target_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_daily_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_daily_shifts_target_date'))
        batch_op.drop_index(batch_op.f('ix_staff_daily_shifts_supporter_id'))
        batch_op.drop_index(batch_op.f('ix_staff_daily_shifts_office_service_configuration_id'))

    op.drop_table('staff_daily_shifts')
    with op.batch_alter_table('staff_daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_daily_reports_target_date'))
        batch_op.drop_index(batch_op.f('ix_staff_daily_reports_supporter_id'))

    op.drop_table('staff_daily_reports')
    with op.batch_alter_table('staff_action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_action_logs_supporter_id'))

    op.drop_table('staff_action_logs')
    # ### end Alembic commands ###
